version: '3.8'

services:
  rabbitmq:
        container_name: rabbit-mq        
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
        ports:
            - '5672:5672'
            - '15672:15672'
        image: 'rabbitmq:latest'

  sqlserver:
        container_name: sql-server
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=strong!Password123
        ports:
            - '1433:1433'
        image: 'mcr.microsoft.com/mssql/server:2022-latest'

  auth_service:
        build:           
          dockerfile: FridgeManager.AuthMicroService/Dockerfile
        environment:
          - "ASPNETCORE_URLS=https://+"
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
        volumes:
            - ~/.aspnet/https:/https:ro
        ports:
            - '5001:443'
        container_name: auth_service_container
        image: auth_service_image
        depends_on:             
             - sqlserver

  products_service:
        build:           
          dockerfile: FridgeManager.ProductsMicroService/Dockerfile
        environment:
          - "ASPNETCORE_URLS=https://+"
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
        volumes:
            - ~/.aspnet/https:/https:ro
        ports:
            - '5002:443'
        container_name: products-service-container
        image: products-service-image
        depends_on:
             - rabbitmq
             - sqlserver

  fridge_service:
        build:           
          dockerfile: FridgeManager.FridgesMicroService/Dockerfile
        environment:
          - "ASPNETCORE_URLS=https://+"
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
        volumes:
            - ~/.aspnet/https:/https:ro
        ports:
            - '5003:443'
        container_name: fridges-service-container
        image: fridges-service-image
        depends_on:
            - rabbitmq
            - sqlserver

  gateway_service:
        build:           
          dockerfile: FridgeManager.OcelotApiGateway/Dockerfile
        environment:
          - "ASPNETCORE_URLS=https://+"
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
        volumes:
            - ~/.aspnet/https:/https:ro
        ports:
            - '5005:443'
        container_name: gateway-container
        image: gateway-image
        depends_on:
            - auth_service
            - products_service
            - fridge_service

  health_service:
        build:           
          dockerfile: FridgeManager.HealthChecks/Dockerfile
        environment:
          - "ASPNETCORE_URLS=https://+"
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
          - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
        volumes:
            - ~/.aspnet/https:/https:ro
        ports:
            - '5006:443'
        container_name: health-container
        image: health-image
        depends_on:
            - auth_service
            - products_service
            - fridge_service
            - gateway_service    