version: '3.8'

services:
  rabbitmq:
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
        image: 'rabbitmq:3.10-management'

  auth_service:
        ports:
            - '5001:80'
        container_name: auth_service
        image: auth_service
        restart: on-failure

  fridge_web:      
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: fridge_web:dev

    