// <auto-generated />
using System;
using Entities.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220901102838_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            FridgeModelId = new Guid("316e7144-85e5-43f5-b96a-9b2221c760c3"),
                            Name = "Beko",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            FridgeModelId = new Guid("316e7144-85e5-43f5-b96a-9b2221c760c3"),
                            Name = "Beko",
                            OwnerName = "Anna"
                        },
                        new
                        {
                            Id = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            FridgeModelId = new Guid("17703f0b-356e-4346-b631-da5965d694f4"),
                            Name = "Vestfrost",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            FridgeModelId = new Guid("959c45ee-9c1e-49d1-9419-8a223f8321b3"),
                            Name = "Bosch",
                            OwnerName = "Vlada"
                        },
                        new
                        {
                            Id = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            FridgeModelId = new Guid("316e7144-85e5-43f5-b96a-9b2221c760c3"),
                            Name = "Atlant",
                            OwnerName = "Dima"
                        });
                });

            modelBuilder.Entity("Entities.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dee19637-d0ba-4f64-9447-ea6d7ed6f703"),
                            Name = "TH-803",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("959c45ee-9c1e-49d1-9419-8a223f8321b3"),
                            Name = "514-NWE",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("96e4de91-d312-4c26-a70c-db38e910d433"),
                            Name = "RC-54",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("316e7144-85e5-43f5-b96a-9b2221c760c3"),
                            Name = "XM 4021-000",
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("c1d2b335-2ee7-41cb-ba39-a5c791703acf"),
                            Name = "DF 5180 W",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("2d11d538-2631-4cff-b94e-2a2d1177ece1"),
                            Name = "DS 333020",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("6bb788cd-ce13-4b02-a781-d621f90b56f3"),
                            Name = "VF 466 EB",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("17703f0b-356e-4346-b631-da5965d694f4"),
                            Name = "KGN36S55",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("46ec6a11-82fd-435b-bc8d-b8231f5be9b1"),
                            Name = "RB-34 K6220SS",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("e676a1ef-978d-431a-b4b3-1ed3367cc7b1"),
                            Name = "VF 910 X",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("0334dc6e-38b3-41c5-96c5-aed580f565a1"),
                            Name = "Electric MR-CR46G-HS-R",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("abf38b3a-4159-4ccb-98aa-5c85d638e9f9"),
                            Name = "RF-61 K90407F",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("77d784a1-95bb-441c-a4c3-9ea117717df0"),
                            Name = "SBS 7212",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("dd6d3261-a876-428c-ae62-f856132fc19d"),
                            Name = "VF 395-1 SBS",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("67126052-b657-42d1-bed9-3799bdab2d3b"),
                            Name = "RSA1SHVB1",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("Entities.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9cc22fb-9f81-400b-9f68-1d54295a958f"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("67edc619-ba82-4673-b60d-0141ea40aa94"),
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("571aae09-8373-45b7-93e1-038df1a1a0eb"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("9a644c45-c42b-4a05-a10f-85708420ed00"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("fdd87339-2fa0-4fdc-b616-9780cc2ad5d9"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("11c41bbc-7476-4fbd-8578-e2f4118dd98d"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("d18b2a83-da75-400d-8802-d14ff9d5aa77"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("691e00fe-486e-426b-88b5-e22218ae16a9"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("07c29fd9-eb43-4db8-ab27-d9ffd2f39486"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("8e55a5d7-7a86-4601-a1fd-717b60759c59"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("16d4f0cc-9d99-4caf-9099-6a7c3e447cef"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("a8e3c5ab-d5df-487d-b1c1-adb71c8a2db0"),
                            Quantity = 55
                        },
                        new
                        {
                            Id = new Guid("addb7ee8-da1d-4a10-a0cf-7505d53966e0"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("deefca7b-019b-491b-97a8-760ae77a9e93"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("f2fe4099-0260-4a8f-b741-2045213e8453"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("490af2c4-4d4f-4cea-b694-8acbcdabafdb"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("5af763a0-0ce9-4770-95aa-561565ccf110"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("aac0d0be-d048-4d2f-a992-8fa97db205e3"),
                            Quantity = 75
                        },
                        new
                        {
                            Id = new Guid("7c3e3f29-d79c-4401-aec9-8da9a3b5ee29"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("490af2c4-4d4f-4cea-b694-8acbcdabafdb"),
                            Quantity = 87
                        },
                        new
                        {
                            Id = new Guid("cc8d517f-29c7-43bc-b41c-0f903c4ad8da"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("b537531e-6533-4d43-9ad7-c5ba00264add"),
                            Quantity = 104
                        },
                        new
                        {
                            Id = new Guid("4a0b2844-db62-4f79-acd1-cb3cf45b845e"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("936ed325-5b21-40fa-8a02-e6acb039143c"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("479a2bf9-6361-4f99-be50-44ff9e198748"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("5738609f-8434-41da-bfe4-c639bf3a8580"),
                            Quantity = 86
                        },
                        new
                        {
                            Id = new Guid("f89fad46-a3e3-4908-b9c2-540a52fc7585"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("21c514ce-a929-4ef3-8527-d22d22b3446c"),
                            Quantity = 47
                        },
                        new
                        {
                            Id = new Guid("08a401b3-3515-441c-b4f0-57d3921dcfb7"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("21c514ce-a929-4ef3-8527-d22d22b3446c"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("9175631f-da85-447d-a1a9-bf4e29073259"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("9a644c45-c42b-4a05-a10f-85708420ed00"),
                            Quantity = 43
                        },
                        new
                        {
                            Id = new Guid("ecd50581-2bda-479e-b901-26ad162f239e"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("57f05516-0ad9-4c47-a30a-9a9686b94293"),
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("77d61171-f2da-41bd-9ced-5c08680da336"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("71eb81fe-f43f-4711-8c47-202d9a5b2832"),
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("b1ea8091-8484-4366-b154-597bda58d051"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("d4b758be-4bcb-4454-9c91-ff760f1cecaf"),
                            Quantity = 75
                        },
                        new
                        {
                            Id = new Guid("4e6b5bb6-7771-493b-b335-e8f68f33a3ab"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("71eb81fe-f43f-4711-8c47-202d9a5b2832"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("2e697fd5-1813-45c3-80a4-fe05da1c8d6d"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("c63bd2ca-edd9-4d36-bd6d-1326551f0c21"),
                            Quantity = 37
                        },
                        new
                        {
                            Id = new Guid("1bd53e3e-8658-4afb-8563-36033740aa62"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("3abdb7f0-5be2-4ef3-b564-7b86ba7282fd"),
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("0306793c-5188-401f-b403-80717f355378"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("4e6ab710-5b9a-4d62-81fe-ca1361f53a75"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("b3936a72-8221-4625-8794-84d228c6a53b"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("d721a6fe-9893-417d-9c83-2ed695b475da"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("3ad9ba21-59fa-42ec-975f-783b1d89853c"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("5eb861be-b8a6-46d5-ae50-f14df27a3b01"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("298e9fc0-c1a1-4d2c-a322-03c1e076b146"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("21f5b513-c80f-4740-9eef-956ba539d517"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("ea285627-6e07-438a-9ba6-26bd70101dd7"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("1ad0298a-a534-4c7f-b5ac-57c777ed8c48"),
                            Quantity = 80
                        },
                        new
                        {
                            Id = new Guid("46b97c9a-3230-4042-86e5-ab861da824bf"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("857bc16b-fadd-4fd4-9327-21011f94f3cc"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("3cbfac1a-f362-4272-830e-0d3c5136c1fc"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("824d13bf-9fea-44fa-a074-b08c82e40634"),
                            Quantity = 37
                        },
                        new
                        {
                            Id = new Guid("ecdd0905-297b-43cf-8053-fae8d34805c2"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("83207418-0efa-4915-ab0e-c01a0660d581"),
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("e4e89544-64b5-46f5-898a-c9724b5749f9"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("11c41bbc-7476-4fbd-8578-e2f4118dd98d"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("dd9429f9-addf-41cc-a18e-ef770e5ff858"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("4fe877bc-f34b-4813-ad46-cfb1470d10c0"),
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("e2838513-c2db-462e-b7d0-d1fb42c27a9b"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("dc2ef7b9-afdd-4bab-b525-e5edadd4ae0d"),
                            Quantity = 63
                        },
                        new
                        {
                            Id = new Guid("4fe4baf3-848a-4fd5-bddd-33a43fd81471"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("fd8eb2a4-5795-4fb1-b765-bd485e4c948e"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("309c2bbf-3f3e-4386-8504-1a0af8f7e09b"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("2d7e09eb-e784-4788-91ce-bf174bd3e801"),
                            Quantity = 37
                        },
                        new
                        {
                            Id = new Guid("b2c95a32-dd21-45bd-bf48-8651d8940ec9"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("4e6ab710-5b9a-4d62-81fe-ca1361f53a75"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("45c299e3-4ec4-40f5-bb4e-ce1b8a4344cb"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("5eb861be-b8a6-46d5-ae50-f14df27a3b01"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("25559d4f-648d-4c06-9ab0-4b8ad7cfcce8"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("fd8eb2a4-5795-4fb1-b765-bd485e4c948e"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("8e679e89-d9e6-4f10-830a-4a12d7f8ec8d"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("13690f61-d0c8-487c-9738-a71e6ddc5945"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("b9e29395-aca0-4b77-92cc-fdd3460c2fa3"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("1e0bc6e0-0ecc-42d8-9ddd-396b70c65251"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("34349bdd-fc76-4461-bfac-3d62786ddfa6"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("2d7e09eb-e784-4788-91ce-bf174bd3e801"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("bf67d65a-234d-4c6c-8c5a-b207a2e9639a"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("1ad0298a-a534-4c7f-b5ac-57c777ed8c48"),
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("1c186e4b-49ca-4417-8129-ea60b0368496"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("c3f712d7-57c3-4116-a525-96dfab9a8b6c"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("7545890c-1302-4550-b8ed-89a906afedb7"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("07bcfe36-9949-4a94-8762-925fff456ec7"),
                            Quantity = 48
                        },
                        new
                        {
                            Id = new Guid("e5d57ad2-da35-4b09-b206-67d3737e6974"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("824d13bf-9fea-44fa-a074-b08c82e40634"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("e8105c69-12fe-448f-8ce6-def1815edc57"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("f99411f4-ffa5-489f-8c4e-a7abb6b5cffc"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("a5075682-c048-49e2-9e29-bf57a5497668"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("1e0bc6e0-0ecc-42d8-9ddd-396b70c65251"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("3f343c77-f255-4cf4-b80b-911872d605aa"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("83207418-0efa-4915-ab0e-c01a0660d581"),
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("56f0db66-3afc-4dc1-8842-7ed7d89bfc39"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("deefca7b-019b-491b-97a8-760ae77a9e93"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("f6fa9a12-0a58-4a20-ad17-cd35ce706f70"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("73463840-fed5-49c2-baad-74ec78e8bd7d"),
                            Quantity = 37
                        },
                        new
                        {
                            Id = new Guid("478d37c5-021a-4f9a-8bb9-7fd969658f6a"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("5738609f-8434-41da-bfe4-c639bf3a8580"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("b4dd0121-f0a1-437a-babb-f5def3312e9b"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("fd8eb2a4-5795-4fb1-b765-bd485e4c948e"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("106494ab-6862-41d6-8f72-3f4e47d29299"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("b537531e-6533-4d43-9ad7-c5ba00264add"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("14a6eeee-ba12-4206-8c0b-47b16fe8b23e"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("857bc16b-fadd-4fd4-9327-21011f94f3cc"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("ce4cb9f0-68e1-4a67-b380-e380edbbdffa"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("8e55a5d7-7a86-4601-a1fd-717b60759c59"),
                            Quantity = 38
                        },
                        new
                        {
                            Id = new Guid("efa2c268-ca98-450f-bebf-31c24beafad4"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("d721a6fe-9893-417d-9c83-2ed695b475da"),
                            Quantity = 46
                        },
                        new
                        {
                            Id = new Guid("1715f479-213a-415e-9bde-061c3defd310"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("f99411f4-ffa5-489f-8c4e-a7abb6b5cffc"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("cdaedf0b-a177-47b4-813f-5461a3e01b54"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("ad3da370-5bf0-49e5-9f14-1ded754f86c7"),
                            Quantity = 56
                        },
                        new
                        {
                            Id = new Guid("ca393048-5d23-45c9-a735-e8c5e8e0f353"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("aac0d0be-d048-4d2f-a992-8fa97db205e3"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("61234fd0-5a9d-47d2-9ad4-67a0713c1c3f"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("b537531e-6533-4d43-9ad7-c5ba00264add"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("d666688a-976a-40f5-affd-ea8a97136145"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("5eb861be-b8a6-46d5-ae50-f14df27a3b01"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("ed5c2749-b461-4b4e-8ef0-b05904f74b4b"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("c63bd2ca-edd9-4d36-bd6d-1326551f0c21"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("17757b3a-7c8a-4af3-8392-5dfeef1bc1d2"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("07bcfe36-9949-4a94-8762-925fff456ec7"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("aac6538c-8170-4300-916d-dfbb7b094158"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("21f5b513-c80f-4740-9eef-956ba539d517"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("6716ceab-6daa-45d7-9985-b99f5b5491f4"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("691e00fe-486e-426b-88b5-e22218ae16a9"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("6671a9db-c6ea-489f-a618-f1234b298d34"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("d4b758be-4bcb-4454-9c91-ff760f1cecaf"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("bc2cae53-b587-43be-8db2-dbf1c90085a7"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("1e0bc6e0-0ecc-42d8-9ddd-396b70c65251"),
                            Quantity = 72
                        },
                        new
                        {
                            Id = new Guid("ca89d08d-c491-4d27-983d-fb432479e559"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("8e55a5d7-7a86-4601-a1fd-717b60759c59"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("beb9a1e9-e84f-4dbb-905a-a6451375e6f3"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("936ed325-5b21-40fa-8a02-e6acb039143c"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("cfc8fa50-4766-48a5-beff-8e483682fba2"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("857bc16b-fadd-4fd4-9327-21011f94f3cc"),
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("7375f864-faa1-47f5-ae59-c5df59c12c3b"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("83207418-0efa-4915-ab0e-c01a0660d581"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("66b1ab32-f212-49f6-8f14-11164b6f261e"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("73463840-fed5-49c2-baad-74ec78e8bd7d"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("40ecb154-694d-4bb2-a3c2-c9b89808754e"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("a8e3c5ab-d5df-487d-b1c1-adb71c8a2db0"),
                            Quantity = 83
                        },
                        new
                        {
                            Id = new Guid("6bee07a2-4c9a-4fab-8f95-467fa1cced7d"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("490af2c4-4d4f-4cea-b694-8acbcdabafdb"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("318561e3-638e-4398-9c4a-db0b5eb79769"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("c3f712d7-57c3-4116-a525-96dfab9a8b6c"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("59c43fe8-1c8d-4ced-bf42-85f51bdc40b1"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("dc2ef7b9-afdd-4bab-b525-e5edadd4ae0d"),
                            Quantity = 45
                        },
                        new
                        {
                            Id = new Guid("6bb45275-8911-4ec0-9483-1bfb6799b930"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("ad3da370-5bf0-49e5-9f14-1ded754f86c7"),
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("510b0207-61e4-483f-a39d-7e1053051b07"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("67edc619-ba82-4673-b60d-0141ea40aa94"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("1748615e-62b6-46e9-bd44-e639ff6afeb4"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("3abdb7f0-5be2-4ef3-b564-7b86ba7282fd"),
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("85152b5e-c05a-480a-8fbd-6c6f163a7bd8"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("f99411f4-ffa5-489f-8c4e-a7abb6b5cffc"),
                            Quantity = 38
                        },
                        new
                        {
                            Id = new Guid("c43c69f6-f19b-46fe-877e-cbecc0f7955a"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("ad3da370-5bf0-49e5-9f14-1ded754f86c7"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("d6798db7-42ca-4444-bd5e-61d6fbe48a10"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("4fe877bc-f34b-4813-ad46-cfb1470d10c0"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("9a08efc7-3383-48c6-be0a-8f1b47098004"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("71eb81fe-f43f-4711-8c47-202d9a5b2832"),
                            Quantity = 48
                        },
                        new
                        {
                            Id = new Guid("41ff12b6-e831-4c7f-868a-610d8bf42aaf"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("deefca7b-019b-491b-97a8-760ae77a9e93"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("d3cf835c-e890-4711-95b0-59ce943511ea"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("9a644c45-c42b-4a05-a10f-85708420ed00"),
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("08690eea-75c5-4ef9-9aad-777e168bfff6"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("dc2ef7b9-afdd-4bab-b525-e5edadd4ae0d"),
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("e16cc505-1f19-4ea2-b942-5637282440c3"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("67edc619-ba82-4673-b60d-0141ea40aa94"),
                            Quantity = 58
                        },
                        new
                        {
                            Id = new Guid("ec6edc6f-ae7d-41c6-9e49-e42b13398dd5"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("63c383fa-60e1-48fc-8b0c-bd1c74978730"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("9d04e7fa-b9b4-40d8-8ef9-0dcef862ea80"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("21f5b513-c80f-4740-9eef-956ba539d517"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("8c7a475d-2cd7-4c15-99ce-438e520fff9b"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("71eb81fe-f43f-4711-8c47-202d9a5b2832"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("da0148f6-5235-4c74-8c93-4a97c026e48b"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("11c41bbc-7476-4fbd-8578-e2f4118dd98d"),
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("7daf72d3-66d9-454a-83db-08021bc27c13"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("4e6ab710-5b9a-4d62-81fe-ca1361f53a75"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("f8192227-19ff-4b63-8992-5e8730bff899"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("63c383fa-60e1-48fc-8b0c-bd1c74978730"),
                            Quantity = 45
                        },
                        new
                        {
                            Id = new Guid("2e41d80c-0887-42fe-aa93-8deeba8cb6eb"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("13690f61-d0c8-487c-9738-a71e6ddc5945"),
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("d02f1e3f-4eb0-406a-9e30-c357b579dd7c"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("63c383fa-60e1-48fc-8b0c-bd1c74978730"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("72721d0c-bc43-42a1-a6c0-96be459db7c5"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("c63bd2ca-edd9-4d36-bd6d-1326551f0c21"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("1d68db1f-5018-4758-8c5d-de5db5403dde"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("5738609f-8434-41da-bfe4-c639bf3a8580"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("a36119b2-ec8d-4fb9-b00c-2f8b76ac3abe"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("d4b758be-4bcb-4454-9c91-ff760f1cecaf"),
                            Quantity = 69
                        },
                        new
                        {
                            Id = new Guid("2a23b31c-7ca7-44af-9fb9-fa11f6139ed4"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("57f05516-0ad9-4c47-a30a-9a9686b94293"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("83083ff4-8054-4bf0-ac05-06552242316f"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("1e0bc6e0-0ecc-42d8-9ddd-396b70c65251"),
                            Quantity = 43
                        },
                        new
                        {
                            Id = new Guid("fee86096-fc5b-44b0-829f-3765c32738a8"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("11c41bbc-7476-4fbd-8578-e2f4118dd98d"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("fb924543-2a81-4d2a-8892-a0dc13901238"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("936ed325-5b21-40fa-8a02-e6acb039143c"),
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("24b26fba-691c-486b-a76f-31bb6b58d4ff"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("57f05516-0ad9-4c47-a30a-9a9686b94293"),
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("ebbab192-7b75-46fd-a6cb-3a35442a9e25"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("83207418-0efa-4915-ab0e-c01a0660d581"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("ce628a7f-eb99-4a6a-aba6-0ef518e04770"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("aac0d0be-d048-4d2f-a992-8fa97db205e3"),
                            Quantity = 52
                        },
                        new
                        {
                            Id = new Guid("41ea8e44-5910-400f-beee-4419e0d83da8"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("57f05516-0ad9-4c47-a30a-9a9686b94293"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("bc0bc117-663c-4543-8d14-bd1ecbd5f82e"),
                            FridgeId = new Guid("220b14ea-114f-4b64-bb53-2f926b77fd7c"),
                            ProductId = new Guid("73463840-fed5-49c2-baad-74ec78e8bd7d"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("60948d88-f977-42dd-91cb-ea846e3a15ba"),
                            FridgeId = new Guid("c01e3b97-3c46-4683-ab34-d99a13c0bd56"),
                            ProductId = new Guid("4fe877bc-f34b-4813-ad46-cfb1470d10c0"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("4ca46cb7-526d-4b8e-a3f3-8b80576edca3"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("a8e3c5ab-d5df-487d-b1c1-adb71c8a2db0"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("377d99ab-4526-470f-a268-cce678cb98c8"),
                            FridgeId = new Guid("b921502a-1964-4033-83d9-885faf12f74d"),
                            ProductId = new Guid("1e0bc6e0-0ecc-42d8-9ddd-396b70c65251"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("a351c925-1028-4604-93d0-d5fb3e1ba354"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("4e6ab710-5b9a-4d62-81fe-ca1361f53a75"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("c965d054-a716-4d65-a8ac-93ae17b5efc5"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("d721a6fe-9893-417d-9c83-2ed695b475da"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("2dd176ec-9303-4c87-a57b-642b8036e228"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("824d13bf-9fea-44fa-a074-b08c82e40634"),
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("eb386c04-f5e6-4104-be30-857f971de7e8"),
                            FridgeId = new Guid("bd38cdb8-0cd4-46b8-a292-d58bd1027d1e"),
                            ProductId = new Guid("691e00fe-486e-426b-88b5-e22218ae16a9"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("00737e29-97f5-4f8f-8445-e8f015f143e9"),
                            FridgeId = new Guid("cffc5731-3af8-4f77-994b-9b9649a60ace"),
                            ProductId = new Guid("07bcfe36-9949-4a94-8762-925fff456ec7"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e55a5d7-7a86-4601-a1fd-717b60759c59"),
                            DefaultQuantity = 16,
                            ImageSource = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Assorted_bread.jpg/274px-Assorted_bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("2d7e09eb-e784-4788-91ce-bf174bd3e801"),
                            DefaultQuantity = 10,
                            ImageSource = "https://id-test-11.slatic.net/p/70f40d8f77f844671af4a5a11755e7ae.jpg",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("691e00fe-486e-426b-88b5-e22218ae16a9"),
                            DefaultQuantity = 17,
                            ImageSource = "https://media.istockphoto.com/vectors/yogurt-cup-with-spoon-vector-id1060883416?k=20&m=1060883416&s=612x612&w=0&h=nhPJA8XYohdkGbBojLt72e_q9sbgBuO6mUI-7cnuu6s=",
                            Name = "Yoghurt"
                        },
                        new
                        {
                            Id = new Guid("13690f61-d0c8-487c-9738-a71e6ddc5945"),
                            DefaultQuantity = 10,
                            ImageSource = "https://www.collinsdictionary.com/images/full/egg_110803370.jpg",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("c3f712d7-57c3-4116-a525-96dfab9a8b6c"),
                            DefaultQuantity = 15,
                            ImageSource = "https://cdn.yamatoscale.com/wp-content/uploads/2016/04/K%C3%A4se-Scheiben_01_00_OH-1.jpg",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("824d13bf-9fea-44fa-a074-b08c82e40634"),
                            DefaultQuantity = 13,
                            ImageSource = "https://4.imimg.com/data4/JX/UQ/ANDROID-47104262/product-500x500.jpeg",
                            Name = "Mashroom"
                        },
                        new
                        {
                            Id = new Guid("f99411f4-ffa5-489f-8c4e-a7abb6b5cffc"),
                            DefaultQuantity = 12,
                            ImageSource = "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/5/1/0/0039592F3_beer-can-chicken_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539274625.jpeg",
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = new Guid("fd8eb2a4-5795-4fb1-b765-bd485e4c948e"),
                            DefaultQuantity = 9,
                            ImageSource = "https://www.thespruceeats.com/thmb/OueG44zJ3LnwQt9HwVXmmT6mkNM=/3067x3067/smart/filters:no_upscale()/roasted-boneless-pork-loin-recipe-995289-hero-01-93314ca221a54ecebc45a17e99cb78c4.jpg",
                            Name = "Pork"
                        },
                        new
                        {
                            Id = new Guid("1e0bc6e0-0ecc-42d8-9ddd-396b70c65251"),
                            DefaultQuantity = 14,
                            ImageSource = "https://hips.hearstapps.com/hmg-prod/images/delish-roast-beef-horizontal-1540505165.jpg",
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("a8e3c5ab-d5df-487d-b1c1-adb71c8a2db0"),
                            DefaultQuantity = 6,
                            ImageSource = "https://www.crescentfoods.lk/images/products/PREMIUM_CHICKEN_SAUSAGES.jpg",
                            Name = "Sausage"
                        },
                        new
                        {
                            Id = new Guid("73463840-fed5-49c2-baad-74ec78e8bd7d"),
                            DefaultQuantity = 11,
                            ImageSource = "https://preview.free3d.com/img/2017/05/2279485108920518249/e92jihnh-900.jpg",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("5eb861be-b8a6-46d5-ae50-f14df27a3b01"),
                            DefaultQuantity = 17,
                            ImageSource = "https://images.absolutdrinks.com/ingredient-images/Raw/Absolut/d391984d-0573-4fb2-aa36-2f18d2ee8ce8.jpg?imwidth=500",
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = new Guid("d721a6fe-9893-417d-9c83-2ed695b475da"),
                            DefaultQuantity = 16,
                            ImageSource = "http://cdn.shopify.com/s/files/1/0404/0710/5687/products/6000200094505_grande.jpg?v=1595626016",
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("11c41bbc-7476-4fbd-8578-e2f4118dd98d"),
                            DefaultQuantity = 8,
                            ImageSource = "https://www.eatthis.com/wp-content/uploads/sites/4/2020/03/variety-of-beans.jpg?quality=82&strip=1",
                            Name = "Beans"
                        },
                        new
                        {
                            Id = new Guid("d4b758be-4bcb-4454-9c91-ff760f1cecaf"),
                            DefaultQuantity = 14,
                            ImageSource = "https://www.jessicagavin.com/wp-content/uploads/2019/02/carrots-7-1200.jpg",
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = new Guid("aac0d0be-d048-4d2f-a992-8fa97db205e3"),
                            DefaultQuantity = 6,
                            ImageSource = "https://www.farmersfamily.in/wp-content/uploads/2020/08/Cucumber.jpg",
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = new Guid("deefca7b-019b-491b-97a8-760ae77a9e93"),
                            DefaultQuantity = 5,
                            ImageSource = "https://produits.bienmanger.com/36700-0w470h470_Organic_Red_Onion_From_Italy.jpg",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = new Guid("4fe877bc-f34b-4813-ad46-cfb1470d10c0"),
                            DefaultQuantity = 13,
                            ImageSource = "https://www.ngroceries.com/wp-content/uploads/2021/10/61amdwJRu-L._SX522_.jpg",
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("3abdb7f0-5be2-4ef3-b564-7b86ba7282fd"),
                            DefaultQuantity = 5,
                            ImageSource = "https://5.imimg.com/data5/ANDROID/Default/2021/2/UH/HH/LB/44089979/potatoes-jpg-250x250.jpg",
                            Name = "Potato"
                        },
                        new
                        {
                            Id = new Guid("c63bd2ca-edd9-4d36-bd6d-1326551f0c21"),
                            DefaultQuantity = 10,
                            ImageSource = "https://images.heb.com/is/image/HEBGrocery/000377497",
                            Name = "Banana"
                        },
                        new
                        {
                            Id = new Guid("21c514ce-a929-4ef3-8527-d22d22b3446c"),
                            DefaultQuantity = 9,
                            ImageSource = "https://sc04.alicdn.com/kf/Ub2b912f5fb6d48ce99dee2bef2a7d2fch.jpg",
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = new Guid("71eb81fe-f43f-4711-8c47-202d9a5b2832"),
                            DefaultQuantity = 8,
                            ImageSource = "https://img.freepik.com/free-vector/isolated-dark-grape-with-green-leaf_317810-1956.jpg?w=2000",
                            Name = "Grape"
                        },
                        new
                        {
                            Id = new Guid("83207418-0efa-4915-ab0e-c01a0660d581"),
                            DefaultQuantity = 6,
                            ImageSource = "https://www.seeds-gallery.shop/8291-large_default/lemon-seeds-c-limon.jpg",
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = new Guid("ad3da370-5bf0-49e5-9f14-1ded754f86c7"),
                            DefaultQuantity = 6,
                            ImageSource = "https://cdn.shopify.com/s/files/1/2971/2126/products/Orange_f48b955f-9cde-4b90-bbd5-03ce7b8bcf1f_400x.jpg?v=1569304785",
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("57f05516-0ad9-4c47-a30a-9a9686b94293"),
                            DefaultQuantity = 6,
                            ImageSource = "https://static.libertyprim.com/files/familles/peche-large.jpg?1574630286",
                            Name = "Peach"
                        },
                        new
                        {
                            Id = new Guid("857bc16b-fadd-4fd4-9327-21011f94f3cc"),
                            DefaultQuantity = 11,
                            ImageSource = "https://befreshcorp.net/wp-content/uploads/2017/07/product-packshot-strawberrie-558x600.jpg",
                            Name = "Strawberry"
                        },
                        new
                        {
                            Id = new Guid("9a644c45-c42b-4a05-a10f-85708420ed00"),
                            DefaultQuantity = 16,
                            ImageSource = "https://soapatopia.com/wp-content/uploads/2021/01/raspberries.jpg",
                            Name = "Raspberry"
                        },
                        new
                        {
                            Id = new Guid("1ad0298a-a534-4c7f-b5ac-57c777ed8c48"),
                            DefaultQuantity = 14,
                            ImageSource = "https://www.seeds-gallery.shop/5488-large_default/400-watermelon-seeds-crimson-sweet.jpg",
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = new Guid("67edc619-ba82-4673-b60d-0141ea40aa94"),
                            DefaultQuantity = 12,
                            ImageSource = "https://quintalsonline.com/wp-content/uploads/2020/05/close-up-of-block-of-butter-being-sliced-may-raise-cholesterol_1400x.jpg",
                            Name = "Butter"
                        },
                        new
                        {
                            Id = new Guid("21f5b513-c80f-4740-9eef-956ba539d517"),
                            DefaultQuantity = 10,
                            ImageSource = "https://static.vecteezy.com/system/resources/previews/006/225/849/original/a-carton-of-milk-cartoon-illustration-vector.jpg",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("b537531e-6533-4d43-9ad7-c5ba00264add"),
                            DefaultQuantity = 8,
                            ImageSource = "https://groceries.morrisons.com/productImages/408/408833011_0_268x268.jpg?identifier=146ae3bbcbb049c8aa859a0fbd47946e",
                            Name = "Kefir"
                        },
                        new
                        {
                            Id = new Guid("936ed325-5b21-40fa-8a02-e6acb039143c"),
                            DefaultQuantity = 12,
                            ImageSource = "https://andygrimshaw.com/wp-content/uploads/2016/03/Chocolate-bar-melt-explosion.jpg",
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = new Guid("dc2ef7b9-afdd-4bab-b525-e5edadd4ae0d"),
                            DefaultQuantity = 17,
                            ImageSource = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/4B7C3510-7041-4B5D-8000-1D10B1BA4678/Derivates/6749ac4e-586d-4055-9df2-5a96832897f6.jpg",
                            Name = "Jam"
                        },
                        new
                        {
                            Id = new Guid("5738609f-8434-41da-bfe4-c639bf3a8580"),
                            DefaultQuantity = 8,
                            ImageSource = "https://www.mybakingaddiction.com/wp-content/uploads/2021/03/vanilla-pudding-with-fruit-720x720.jpg",
                            Name = "Pudding"
                        },
                        new
                        {
                            Id = new Guid("490af2c4-4d4f-4cea-b694-8acbcdabafdb"),
                            DefaultQuantity = 6,
                            ImageSource = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/607dfd53-5b5c-4309-9e1f-5a959d20e16c/Derivates/9ac9e3c1-20d2-4d31-afdb-191c9ba22235.jpg",
                            Name = "Jelly"
                        },
                        new
                        {
                            Id = new Guid("63c383fa-60e1-48fc-8b0c-bd1c74978730"),
                            DefaultQuantity = 7,
                            ImageSource = "https://www.wholesomeyum.com/wp-content/uploads/2017/03/wholesomeyum-Low-Carb-Keto-Pancakes-Recipe-21.jpg",
                            Name = "Pancake"
                        },
                        new
                        {
                            Id = new Guid("4e6ab710-5b9a-4d62-81fe-ca1361f53a75"),
                            DefaultQuantity = 12,
                            ImageSource = "https://media.istockphoto.com/photos/fresh-citrus-juices-picture-id158268808?k=20&m=158268808&s=612x612&w=0&h=9mUMCBDaY-JYqR7m9r_mi0-Ta0RIebZ3DpxyimSQ7Fc=",
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("07bcfe36-9949-4a94-8762-925fff456ec7"),
                            DefaultQuantity = 16,
                            ImageSource = "https://img.freepik.com/free-vector/soda-cups-drink_24877-57922.jpg?w=2000",
                            Name = "Soda"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "218726a2-a1f9-4c41-b1f6-8075767d2c19",
                            ConcurrencyStamp = "bfbebcc9-ffe5-498d-bd01-44c73133d7d4",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "624e7a25-711a-4935-bde8-f035a19dc6c3",
                            ConcurrencyStamp = "38cb36b8-b870-43c7-888a-bff564eda798",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.HasOne("Entities.Models.FridgeModel", "FridgeModel")
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeModel");
                });

            modelBuilder.Entity("Entities.Models.FridgeProduct", b =>
                {
                    b.HasOne("Entities.Models.Fridge", "Fridge")
                        .WithMany("Products")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Fridges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.FridgeModel", b =>
                {
                    b.Navigation("Fridges");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Fridges");
                });
#pragma warning restore 612, 618
        }
    }
}
