// <auto-generated />
using System;
using Entities.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220830184404_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            FridgeModelId = new Guid("099bf9c9-3541-44e2-8684-b4a45a65465a"),
                            Name = "Atlant",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            FridgeModelId = new Guid("30482cbb-33a5-4c17-b8c7-717ae49fb48a"),
                            Name = "Liebherr",
                            OwnerName = "Anna"
                        },
                        new
                        {
                            Id = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            FridgeModelId = new Guid("3836cb84-7fb4-45eb-9953-8c63279d4319"),
                            Name = "Liebherr",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            FridgeModelId = new Guid("cfdc5da0-9618-4034-8662-b39f38ca6be2"),
                            Name = "Stinol",
                            OwnerName = "Vlada"
                        },
                        new
                        {
                            Id = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            FridgeModelId = new Guid("30482cbb-33a5-4c17-b8c7-717ae49fb48a"),
                            Name = "Atlant",
                            OwnerName = "Anna"
                        });
                });

            modelBuilder.Entity("Entities.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f80a6ac5-72f5-4ed0-a938-f66570d41845"),
                            Name = "TH-803",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("801e7585-c0e5-48ab-862c-3e0f26eee8e7"),
                            Name = "514-NWE",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("3fdbd942-377d-4334-a4a6-a136c362ee17"),
                            Name = "RC-54",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("24c1b9b9-a1f1-4a08-bbe6-7f55548bc656"),
                            Name = "XM 4021-000",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("e8ee1f79-972d-498b-9ad6-eb54128a81bc"),
                            Name = "DF 5180 W",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("85445561-627a-4899-aa62-d269224a0198"),
                            Name = "DS 333020",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("a3640b1d-f1f0-49ad-b1ba-b0e7538d91c0"),
                            Name = "VF 466 EB",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("1360d01f-c99a-4a59-b4bf-642f8fa403ba"),
                            Name = "KGN36S55",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("3836cb84-7fb4-45eb-9953-8c63279d4319"),
                            Name = "RB-34 K6220SS",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("cfdc5da0-9618-4034-8662-b39f38ca6be2"),
                            Name = "VF 910 X",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("30482cbb-33a5-4c17-b8c7-717ae49fb48a"),
                            Name = "Electric MR-CR46G-HS-R",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("357c2fc4-6dd9-4834-a914-8d75d6826cd8"),
                            Name = "RF-61 K90407F",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("099bf9c9-3541-44e2-8684-b4a45a65465a"),
                            Name = "SBS 7212",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("aa910856-3eb5-4da1-a2f4-5362266e3add"),
                            Name = "VF 395-1 SBS",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("23abc33d-5f5c-4aaa-86f0-84f2f91c5d6c"),
                            Name = "RSA1SHVB1",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("Entities.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ae65398-5729-45e5-a963-e1d268ba6d20"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("abfd8d4c-01a1-44cf-9aee-9df17b295902"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("08da333e-4cab-468a-8817-1c9275b8ef96"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("6456db6c-0656-4213-b64c-34c776f9f4f7"),
                            Quantity = 56
                        },
                        new
                        {
                            Id = new Guid("4cb00569-4fea-448c-af66-b463365fbe17"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("9d8ea165-d819-42be-9c33-785048e9fb35"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("9a623512-0aec-4dc8-b902-b33b3409e122"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("5e47f106-4a55-4542-a656-c49a71b0ede3"),
                            Quantity = 65
                        },
                        new
                        {
                            Id = new Guid("5712946b-bf8c-4778-a877-5848a144ca5f"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("2a6a9318-e7d5-4ea9-9c0f-8c8101bad32d"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("d4ea3723-742a-4bc8-8607-b556477b399d"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("76295722-b3bb-40f6-8996-8790fd8fa611"),
                            Quantity = 71
                        },
                        new
                        {
                            Id = new Guid("a7307b5e-19f5-458a-9f2c-0a4b76348987"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("8ee72798-bdf7-4871-a94a-02fc34c8f501"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("32b9296b-edbe-4bb2-8b94-8a8dc4170285"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("e758f9db-8764-455f-8859-11ecd11cf977"),
                            Quantity = 45
                        },
                        new
                        {
                            Id = new Guid("2e1a9e80-b946-4302-a43c-87daafc10452"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("e118f4b9-c28f-4253-bc9a-55e35170541c"),
                            Quantity = 104
                        },
                        new
                        {
                            Id = new Guid("5a7e16a0-e28d-4a98-9abc-688234c509a0"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("5e761121-326a-49e3-9170-da8b8631dcb6"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("66dac321-d4c7-4ad3-b4c9-db75243d6762"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("f32c8667-8c8a-46de-866a-f8888e518b8f"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("5732fae5-cb36-4286-abce-9a9301ea67bc"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("7ccc317c-6ddf-4bdb-bdbc-c5b647f68f35"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("2e4aa706-2910-465f-bd64-203df3d36402"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("b6df4f09-41c3-4704-9ba5-a2829f695ae4"),
                            Quantity = 58
                        },
                        new
                        {
                            Id = new Guid("50870991-aa0e-4569-99c9-baee55e31dc4"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("8ee72798-bdf7-4871-a94a-02fc34c8f501"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("4aab5a74-268a-4ec1-9078-52635f214668"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("3e66d4df-070b-452c-b016-a9f20f309c2a"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("1be04df6-2ecf-4721-928e-a7e251213536"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("6423ad10-758d-4a16-b2d5-36b6f3138290"),
                            Quantity = 44
                        },
                        new
                        {
                            Id = new Guid("8db0c401-4107-4ac0-bad9-d27ddba7fbc0"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("b7e10d92-d054-41d6-9238-2b000d3cad7a"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("79314478-64cf-404f-a076-ab4b15b1c89d"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("7ccc317c-6ddf-4bdb-bdbc-c5b647f68f35"),
                            Quantity = 44
                        },
                        new
                        {
                            Id = new Guid("9f374111-5612-4e7a-95b9-59aa1f0dfba8"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("92d00395-2800-4b4f-974e-18b27f27e525"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("675539fe-4033-46cf-9da2-15136d105964"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("048d4efc-089b-453b-b778-a65d8c5e3d21"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("5f2a3285-77dd-43dd-84ec-e20a0ccedaf7"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("5eb62c67-8488-435c-821f-505779e9b43e"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("62ec2c8f-5b55-4ba5-80b4-ac0b13461750"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("d5d582a4-0a16-4c8e-b680-dc1711c1867d"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("800d11b3-d9e1-463a-82f3-59e290327c58"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("48cd87ec-0fa5-4725-8f8c-4b018aa8609a"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("570ed20a-0f6b-4079-ac38-5027d796df7a"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("780d00bb-7681-440a-8948-0db6091c8785"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("31c37a32-b9b5-4e98-a620-8c53e8ac5397"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("b7e10d92-d054-41d6-9238-2b000d3cad7a"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("a84a735d-9784-46db-8d2b-8b8152d9bb74"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("b6df4f09-41c3-4704-9ba5-a2829f695ae4"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("5ee07599-dc16-407f-ac7e-3bd86b3db9ca"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("5d87fa2a-7402-4796-a154-6fd7347023fa"),
                            Quantity = 38
                        },
                        new
                        {
                            Id = new Guid("bc7708fe-3f5a-4e39-9437-34c534aa73ff"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("e3127588-62ed-4459-bbf5-562030ef456c"),
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("a65a9014-05d1-4c9a-84e4-c4dbdf025b28"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("9d8ea165-d819-42be-9c33-785048e9fb35"),
                            Quantity = 71
                        },
                        new
                        {
                            Id = new Guid("8fe92ca8-6658-4412-b697-1a60b242d3e1"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("fd89d73f-8b12-4a4b-bbd7-01b340b83718"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("74e5a977-aab9-48bf-857d-418400c02410"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("3e883ff9-9a14-467d-9442-4913487ceb4b"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("e8ad185c-6ae9-425e-a4e5-ddceb5648138"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("5eb62c67-8488-435c-821f-505779e9b43e"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("c1d22e43-22c8-4624-93ab-b929b7eae692"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("b6df4f09-41c3-4704-9ba5-a2829f695ae4"),
                            Quantity = 81
                        },
                        new
                        {
                            Id = new Guid("18312109-6b6e-419a-902c-685472ed25d4"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("fd89d73f-8b12-4a4b-bbd7-01b340b83718"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("8ec95f12-336f-4765-938c-6abceae44b2f"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("8ee72798-bdf7-4871-a94a-02fc34c8f501"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("0a86d9fc-4b63-420a-85bc-c1d409a508ec"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("76295722-b3bb-40f6-8996-8790fd8fa611"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("801e30ce-9260-4214-a3da-1d8abc1858c1"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("4495956c-4cd1-485a-a696-ac268df6a414"),
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("0ee84cbb-ff60-40ba-a3da-3633ef466251"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("8a794cbe-0bdf-43dc-9553-f8101f49371b"),
                            Quantity = 77
                        },
                        new
                        {
                            Id = new Guid("03130250-6158-4049-bd73-ba54684eb3fe"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("d4017dae-7d91-4aed-a5ce-2b46c5eada93"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("08837fba-3aaf-482d-9b80-c11871d8bb1b"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("a53daaf3-9eaa-4736-b5e8-6de65e45e4ec"),
                            Quantity = 72
                        },
                        new
                        {
                            Id = new Guid("9cc3dd34-785c-458c-b619-ff787a32e0bf"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("f86fa4a0-fe03-4f3f-8b22-de1ccaa0231d"),
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("bd748b20-c2ce-4107-bd7d-d39a7a2da631"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("d1ee06ed-55fd-4d16-8f6e-8a61a8f59d9f"),
                            Quantity = 61
                        },
                        new
                        {
                            Id = new Guid("cd820b2b-76d3-478e-a173-fbdd3beec491"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("f32c8667-8c8a-46de-866a-f8888e518b8f"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("3087c5d3-2092-4361-88d4-28a5a38bb741"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("9d8ea165-d819-42be-9c33-785048e9fb35"),
                            Quantity = 63
                        },
                        new
                        {
                            Id = new Guid("4da5d668-b6a6-4cb7-982a-7fc56773c597"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("d4017dae-7d91-4aed-a5ce-2b46c5eada93"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("85455191-ceb7-4124-b0d8-aef8530c6d9d"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("3e883ff9-9a14-467d-9442-4913487ceb4b"),
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("54c33fed-d54d-4683-81d2-6f5388b383a2"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("f0ddb097-faab-41e2-b6fd-8c7475e92d0c"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("77fbc271-952d-4332-ad1b-f2f7e170b7a6"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("7100222f-745f-446a-a519-15b218c62e57"),
                            Quantity = 71
                        },
                        new
                        {
                            Id = new Guid("89494be0-7090-4e99-a9aa-9d901a1fe066"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("048d4efc-089b-453b-b778-a65d8c5e3d21"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("37a1079c-c06d-45dd-ad97-96ccc42c1b93"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("8a794cbe-0bdf-43dc-9553-f8101f49371b"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("7ab34090-52de-497a-ac6a-660d5f14f7df"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("f86fa4a0-fe03-4f3f-8b22-de1ccaa0231d"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("ea7aa4d4-7c7f-46a5-920b-3e0ff2fb77dc"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("5eb62c67-8488-435c-821f-505779e9b43e"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("781ee8f1-bb5f-4ab2-87bc-d63977db63c1"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("5ead8209-d653-4bb9-af6a-5fbf888a9f18"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("232eb078-7d30-49ed-8913-b124d43ae7b0"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("5e761121-326a-49e3-9170-da8b8631dcb6"),
                            Quantity = 47
                        },
                        new
                        {
                            Id = new Guid("cdd7f608-e356-4bef-9e74-eeb252c4de34"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("5d87fa2a-7402-4796-a154-6fd7347023fa"),
                            Quantity = 46
                        },
                        new
                        {
                            Id = new Guid("ef8ec41c-3eac-410f-b715-018012f5f827"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("5e47f106-4a55-4542-a656-c49a71b0ede3"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("b0f7230e-dd32-4118-adaa-e95471b8fbeb"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("3e883ff9-9a14-467d-9442-4913487ceb4b"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("a0ad6a6a-3f0d-419b-88f6-b62d3f3163ea"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("8a794cbe-0bdf-43dc-9553-f8101f49371b"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("4e8f6b1d-fe59-4611-844c-fcdbd4422137"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("d5d582a4-0a16-4c8e-b680-dc1711c1867d"),
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("0b83c109-7cb4-4ff8-91ce-8896ea7d709b"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("1fa563d3-936b-4217-a200-2d514dd33f94"),
                            Quantity = 36
                        },
                        new
                        {
                            Id = new Guid("74587077-1991-491f-adcd-644bbae18cf2"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("3e66d4df-070b-452c-b016-a9f20f309c2a"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("a62ef07c-ba75-46ce-aaff-78e84165c2eb"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("e758f9db-8764-455f-8859-11ecd11cf977"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("a83fe128-6ef9-4ed5-a28d-3aebef8510bb"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("7ccc317c-6ddf-4bdb-bdbc-c5b647f68f35"),
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("e3d40398-8c18-4507-96d5-8bc8e47aa792"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("92d00395-2800-4b4f-974e-18b27f27e525"),
                            Quantity = 72
                        },
                        new
                        {
                            Id = new Guid("5e86a0f3-9e8d-4dc1-95ba-de1f10d7181e"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("f0ddb097-faab-41e2-b6fd-8c7475e92d0c"),
                            Quantity = 45
                        },
                        new
                        {
                            Id = new Guid("f8197c3a-97fe-42d4-aaac-9ef6f22eebc6"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("e118f4b9-c28f-4253-bc9a-55e35170541c"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("89c29461-b104-40aa-9345-966b7b6b18e6"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("4495956c-4cd1-485a-a696-ac268df6a414"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("b52fa428-a4a6-46b7-96d4-1066173ed78a"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("6423ad10-758d-4a16-b2d5-36b6f3138290"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("9704bb4c-ee6b-41ae-91c6-848cd4d486d7"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("3e66d4df-070b-452c-b016-a9f20f309c2a"),
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("12707ec3-79a1-4e2f-8405-358a1a82fc64"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("e758f9db-8764-455f-8859-11ecd11cf977"),
                            Quantity = 36
                        },
                        new
                        {
                            Id = new Guid("3f0cb6bd-c176-42b5-b55d-4e54c68888d8"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("7100222f-745f-446a-a519-15b218c62e57"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("a7e26c3f-fad0-436e-bb6a-ea760c483da1"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("5e761121-326a-49e3-9170-da8b8631dcb6"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("478a2b52-b487-4697-adab-02526187638f"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("2a6a9318-e7d5-4ea9-9c0f-8c8101bad32d"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("3cb422d3-0b5d-44fd-81a2-f9bc319bf123"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("780d00bb-7681-440a-8948-0db6091c8785"),
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("fbde641f-1b53-4fe0-b478-3bb540880d4c"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("f4e5d78c-344b-4126-9ac8-58bbb0fac6a6"),
                            Quantity = 37
                        },
                        new
                        {
                            Id = new Guid("6498ba06-ddb8-4473-af3d-e7ad87b83baf"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("54eee9f5-b83c-4344-aaf9-5aa0262e33d8"),
                            Quantity = 67
                        },
                        new
                        {
                            Id = new Guid("a15cf4a1-a629-4763-977e-65cf0802cc64"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("fd89d73f-8b12-4a4b-bbd7-01b340b83718"),
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("bdba9215-f3bf-44eb-bf3c-a25fa3f084af"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("6456db6c-0656-4213-b64c-34c776f9f4f7"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("075ddcff-bc42-41ac-bf48-471fc2e8a112"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("48cd87ec-0fa5-4725-8f8c-4b018aa8609a"),
                            Quantity = 52
                        },
                        new
                        {
                            Id = new Guid("2843975d-da36-4643-ada3-69d377038018"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("f86fa4a0-fe03-4f3f-8b22-de1ccaa0231d"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("d8ffe227-ee80-48fb-883f-1de883b0b10e"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("54eee9f5-b83c-4344-aaf9-5aa0262e33d8"),
                            Quantity = 43
                        },
                        new
                        {
                            Id = new Guid("b34e0090-9cdf-4ca2-b70b-04554c390ced"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("f86fa4a0-fe03-4f3f-8b22-de1ccaa0231d"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("a21a4e36-aee9-4085-8617-1f6ab4e5a0cf"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("e118f4b9-c28f-4253-bc9a-55e35170541c"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("1c8f84a9-1f16-4f59-a715-0dd6272378fc"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("e3127588-62ed-4459-bbf5-562030ef456c"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("c1792ad2-d4fd-4df1-8cb9-5ca663bd3c3f"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("5e761121-326a-49e3-9170-da8b8631dcb6"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("bdf697f6-599a-40e4-86cb-411740865f34"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("a53daaf3-9eaa-4736-b5e8-6de65e45e4ec"),
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("7dc48664-812c-45b0-8587-c3f4a243cfc8"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("abfd8d4c-01a1-44cf-9aee-9df17b295902"),
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0e9ea19-860e-4cec-a7e7-d061dace9ffb"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("1fa563d3-936b-4217-a200-2d514dd33f94"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("9876bd7d-a846-4db9-972f-023c3955afb2"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("a53daaf3-9eaa-4736-b5e8-6de65e45e4ec"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("d99e9644-9365-4212-a17f-b2375ce779cc"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("f4e5d78c-344b-4126-9ac8-58bbb0fac6a6"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("7336b94b-75c7-448c-91df-535fc614e65f"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("f4e5d78c-344b-4126-9ac8-58bbb0fac6a6"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("a87ad84b-6095-499e-9cc7-ac8e5f1ef56f"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("d1ee06ed-55fd-4d16-8f6e-8a61a8f59d9f"),
                            Quantity = 46
                        },
                        new
                        {
                            Id = new Guid("28d5eea1-184d-49d9-8d29-0dba07bf166d"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("e758f9db-8764-455f-8859-11ecd11cf977"),
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("529f8c5f-359b-4a78-abf6-c426345d968f"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("5ead8209-d653-4bb9-af6a-5fbf888a9f18"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("34c9d737-d5e9-40c3-8776-074f2800f013"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("d4017dae-7d91-4aed-a5ce-2b46c5eada93"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("b50c3c12-176d-4540-8f9f-01e40bd14571"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("6423ad10-758d-4a16-b2d5-36b6f3138290"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("46167141-da16-4bab-9ea6-d0062f1ec8d8"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("abfd8d4c-01a1-44cf-9aee-9df17b295902"),
                            Quantity = 38
                        },
                        new
                        {
                            Id = new Guid("3f58415a-8c83-4a5d-88fc-f80b85e8759d"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("6456db6c-0656-4213-b64c-34c776f9f4f7"),
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("0bdd0107-3e7e-492a-9ab8-2ad81ec17ad6"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("5ead8209-d653-4bb9-af6a-5fbf888a9f18"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("3fa303bc-bc17-430c-9e66-55da0e44bf80"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("54eee9f5-b83c-4344-aaf9-5aa0262e33d8"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("5904aeab-6232-419f-b5e7-3c7c92866d68"),
                            FridgeId = new Guid("6d4a1831-0793-4282-ad4c-3f023b60a3b9"),
                            ProductId = new Guid("4495956c-4cd1-485a-a696-ac268df6a414"),
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("db2174aa-bc86-481f-9a8c-9da9bede44d5"),
                            FridgeId = new Guid("2604a4f5-e679-4cbb-93fe-94011f32e49f"),
                            ProductId = new Guid("5d87fa2a-7402-4796-a154-6fd7347023fa"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("ca132267-27fe-4fce-b72e-ceabddd3dfc9"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("780d00bb-7681-440a-8948-0db6091c8785"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("6f9f36d5-09ff-400b-a8ce-d25d95f01d12"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("76295722-b3bb-40f6-8996-8790fd8fa611"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("7036bbc9-8d1c-4b6d-8cb1-5a213971e67f"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("92d00395-2800-4b4f-974e-18b27f27e525"),
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("ae8e2b99-c136-4a77-946d-aac9555d3f91"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("3e66d4df-070b-452c-b016-a9f20f309c2a"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("5232a64f-ee12-4fe5-b875-2784ac5eac88"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("48cd87ec-0fa5-4725-8f8c-4b018aa8609a"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("4dd53005-7301-4698-a8eb-decb47df4d5e"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("d1ee06ed-55fd-4d16-8f6e-8a61a8f59d9f"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("9a19f53e-d837-433e-bca0-d6aff1d6c231"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("a53daaf3-9eaa-4736-b5e8-6de65e45e4ec"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("a4416ece-f182-417d-8b8a-73ff1683a4f2"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("f0ddb097-faab-41e2-b6fd-8c7475e92d0c"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("a90a3daf-b9ad-482e-bbf9-137c20cec695"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("d1ee06ed-55fd-4d16-8f6e-8a61a8f59d9f"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("3f00c554-bf0c-40c6-92e1-4cd4b295f1ce"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("54eee9f5-b83c-4344-aaf9-5aa0262e33d8"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("4b4e7fb5-89a8-4124-b344-80fd7c0e2ee9"),
                            FridgeId = new Guid("433c50a3-018b-475e-b0a5-e391f0c1fe6a"),
                            ProductId = new Guid("3e883ff9-9a14-467d-9442-4913487ceb4b"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("23f545d2-fd29-4c3c-8f8f-736f9b083319"),
                            FridgeId = new Guid("b7392bbc-adb4-4baa-8709-7b03d7900110"),
                            ProductId = new Guid("e3127588-62ed-4459-bbf5-562030ef456c"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("1d2dc83c-54df-4201-a49c-8db37e688450"),
                            FridgeId = new Guid("6966df84-13ad-4f0e-ad8a-8eb46001c17e"),
                            ProductId = new Guid("abfd8d4c-01a1-44cf-9aee-9df17b295902"),
                            Quantity = 11
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7e10d92-d054-41d6-9238-2b000d3cad7a"),
                            DefaultQuantity = 7,
                            ImageSource = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Assorted_bread.jpg/274px-Assorted_bread.jpg",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("76295722-b3bb-40f6-8996-8790fd8fa611"),
                            DefaultQuantity = 17,
                            ImageSource = "https://id-test-11.slatic.net/p/70f40d8f77f844671af4a5a11755e7ae.jpg",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("fd89d73f-8b12-4a4b-bbd7-01b340b83718"),
                            DefaultQuantity = 17,
                            ImageSource = "https://media.istockphoto.com/vectors/yogurt-cup-with-spoon-vector-id1060883416?k=20&m=1060883416&s=612x612&w=0&h=nhPJA8XYohdkGbBojLt72e_q9sbgBuO6mUI-7cnuu6s=",
                            Name = "Yoghurt"
                        },
                        new
                        {
                            Id = new Guid("d4017dae-7d91-4aed-a5ce-2b46c5eada93"),
                            DefaultQuantity = 9,
                            ImageSource = "https://www.collinsdictionary.com/images/full/egg_110803370.jpg",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("5eb62c67-8488-435c-821f-505779e9b43e"),
                            DefaultQuantity = 8,
                            ImageSource = "https://cdn.yamatoscale.com/wp-content/uploads/2016/04/K%C3%A4se-Scheiben_01_00_OH-1.jpg",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("6423ad10-758d-4a16-b2d5-36b6f3138290"),
                            DefaultQuantity = 6,
                            ImageSource = "https://4.imimg.com/data4/JX/UQ/ANDROID-47104262/product-500x500.jpeg",
                            Name = "Mashroom"
                        },
                        new
                        {
                            Id = new Guid("b6df4f09-41c3-4704-9ba5-a2829f695ae4"),
                            DefaultQuantity = 16,
                            ImageSource = "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/5/1/0/0039592F3_beer-can-chicken_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539274625.jpeg",
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = new Guid("abfd8d4c-01a1-44cf-9aee-9df17b295902"),
                            DefaultQuantity = 15,
                            ImageSource = "https://www.thespruceeats.com/thmb/OueG44zJ3LnwQt9HwVXmmT6mkNM=/3067x3067/smart/filters:no_upscale()/roasted-boneless-pork-loin-recipe-995289-hero-01-93314ca221a54ecebc45a17e99cb78c4.jpg",
                            Name = "Pork"
                        },
                        new
                        {
                            Id = new Guid("d1ee06ed-55fd-4d16-8f6e-8a61a8f59d9f"),
                            DefaultQuantity = 14,
                            ImageSource = "https://hips.hearstapps.com/hmg-prod/images/delish-roast-beef-horizontal-1540505165.jpg",
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("2a6a9318-e7d5-4ea9-9c0f-8c8101bad32d"),
                            DefaultQuantity = 12,
                            ImageSource = "https://www.crescentfoods.lk/images/products/PREMIUM_CHICKEN_SAUSAGES.jpg",
                            Name = "Sausage"
                        },
                        new
                        {
                            Id = new Guid("3e66d4df-070b-452c-b016-a9f20f309c2a"),
                            DefaultQuantity = 16,
                            ImageSource = "https://preview.free3d.com/img/2017/05/2279485108920518249/e92jihnh-900.jpg",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("f0ddb097-faab-41e2-b6fd-8c7475e92d0c"),
                            DefaultQuantity = 9,
                            ImageSource = "https://images.absolutdrinks.com/ingredient-images/Raw/Absolut/d391984d-0573-4fb2-aa36-2f18d2ee8ce8.jpg?imwidth=500",
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = new Guid("9d8ea165-d819-42be-9c33-785048e9fb35"),
                            DefaultQuantity = 8,
                            ImageSource = "http://cdn.shopify.com/s/files/1/0404/0710/5687/products/6000200094505_grande.jpg?v=1595626016",
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("f86fa4a0-fe03-4f3f-8b22-de1ccaa0231d"),
                            DefaultQuantity = 13,
                            ImageSource = "https://www.eatthis.com/wp-content/uploads/sites/4/2020/03/variety-of-beans.jpg?quality=82&strip=1",
                            Name = "Beans"
                        },
                        new
                        {
                            Id = new Guid("4495956c-4cd1-485a-a696-ac268df6a414"),
                            DefaultQuantity = 12,
                            ImageSource = "https://www.jessicagavin.com/wp-content/uploads/2019/02/carrots-7-1200.jpg",
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = new Guid("e118f4b9-c28f-4253-bc9a-55e35170541c"),
                            DefaultQuantity = 10,
                            ImageSource = "https://www.farmersfamily.in/wp-content/uploads/2020/08/Cucumber.jpg",
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = new Guid("a53daaf3-9eaa-4736-b5e8-6de65e45e4ec"),
                            DefaultQuantity = 9,
                            ImageSource = "https://produits.bienmanger.com/36700-0w470h470_Organic_Red_Onion_From_Italy.jpg",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = new Guid("8ee72798-bdf7-4871-a94a-02fc34c8f501"),
                            DefaultQuantity = 14,
                            ImageSource = "https://www.ngroceries.com/wp-content/uploads/2021/10/61amdwJRu-L._SX522_.jpg",
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("e3127588-62ed-4459-bbf5-562030ef456c"),
                            DefaultQuantity = 12,
                            ImageSource = "https://5.imimg.com/data5/ANDROID/Default/2021/2/UH/HH/LB/44089979/potatoes-jpg-250x250.jpg",
                            Name = "Potato"
                        },
                        new
                        {
                            Id = new Guid("780d00bb-7681-440a-8948-0db6091c8785"),
                            DefaultQuantity = 17,
                            ImageSource = "https://images.heb.com/is/image/HEBGrocery/000377497",
                            Name = "Banana"
                        },
                        new
                        {
                            Id = new Guid("1fa563d3-936b-4217-a200-2d514dd33f94"),
                            DefaultQuantity = 16,
                            ImageSource = "https://sc04.alicdn.com/kf/Ub2b912f5fb6d48ce99dee2bef2a7d2fch.jpg",
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = new Guid("5ead8209-d653-4bb9-af6a-5fbf888a9f18"),
                            DefaultQuantity = 14,
                            ImageSource = "https://img.freepik.com/free-vector/isolated-dark-grape-with-green-leaf_317810-1956.jpg?w=2000",
                            Name = "Grape"
                        },
                        new
                        {
                            Id = new Guid("5d87fa2a-7402-4796-a154-6fd7347023fa"),
                            DefaultQuantity = 6,
                            ImageSource = "https://www.seeds-gallery.shop/8291-large_default/lemon-seeds-c-limon.jpg",
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = new Guid("48cd87ec-0fa5-4725-8f8c-4b018aa8609a"),
                            DefaultQuantity = 5,
                            ImageSource = "https://cdn.shopify.com/s/files/1/2971/2126/products/Orange_f48b955f-9cde-4b90-bbd5-03ce7b8bcf1f_400x.jpg?v=1569304785",
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("7100222f-745f-446a-a519-15b218c62e57"),
                            DefaultQuantity = 10,
                            ImageSource = "https://static.libertyprim.com/files/familles/peche-large.jpg?1574630286",
                            Name = "Peach"
                        },
                        new
                        {
                            Id = new Guid("8a794cbe-0bdf-43dc-9553-f8101f49371b"),
                            DefaultQuantity = 10,
                            ImageSource = "https://befreshcorp.net/wp-content/uploads/2017/07/product-packshot-strawberrie-558x600.jpg",
                            Name = "Strawberry"
                        },
                        new
                        {
                            Id = new Guid("048d4efc-089b-453b-b778-a65d8c5e3d21"),
                            DefaultQuantity = 14,
                            ImageSource = "https://soapatopia.com/wp-content/uploads/2021/01/raspberries.jpg",
                            Name = "Raspberry"
                        },
                        new
                        {
                            Id = new Guid("f32c8667-8c8a-46de-866a-f8888e518b8f"),
                            DefaultQuantity = 13,
                            ImageSource = "https://www.seeds-gallery.shop/5488-large_default/400-watermelon-seeds-crimson-sweet.jpg",
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = new Guid("92d00395-2800-4b4f-974e-18b27f27e525"),
                            DefaultQuantity = 6,
                            ImageSource = "https://quintalsonline.com/wp-content/uploads/2020/05/close-up-of-block-of-butter-being-sliced-may-raise-cholesterol_1400x.jpg",
                            Name = "Butter"
                        },
                        new
                        {
                            Id = new Guid("7ccc317c-6ddf-4bdb-bdbc-c5b647f68f35"),
                            DefaultQuantity = 17,
                            ImageSource = "https://static.vecteezy.com/system/resources/previews/006/225/849/original/a-carton-of-milk-cartoon-illustration-vector.jpg",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("f4e5d78c-344b-4126-9ac8-58bbb0fac6a6"),
                            DefaultQuantity = 15,
                            ImageSource = "https://groceries.morrisons.com/productImages/408/408833011_0_268x268.jpg?identifier=146ae3bbcbb049c8aa859a0fbd47946e",
                            Name = "Kefir"
                        },
                        new
                        {
                            Id = new Guid("5e761121-326a-49e3-9170-da8b8631dcb6"),
                            DefaultQuantity = 13,
                            ImageSource = "https://andygrimshaw.com/wp-content/uploads/2016/03/Chocolate-bar-melt-explosion.jpg",
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = new Guid("6456db6c-0656-4213-b64c-34c776f9f4f7"),
                            DefaultQuantity = 11,
                            ImageSource = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/4B7C3510-7041-4B5D-8000-1D10B1BA4678/Derivates/6749ac4e-586d-4055-9df2-5a96832897f6.jpg",
                            Name = "Jam"
                        },
                        new
                        {
                            Id = new Guid("54eee9f5-b83c-4344-aaf9-5aa0262e33d8"),
                            DefaultQuantity = 16,
                            ImageSource = "https://www.mybakingaddiction.com/wp-content/uploads/2021/03/vanilla-pudding-with-fruit-720x720.jpg",
                            Name = "Pudding"
                        },
                        new
                        {
                            Id = new Guid("5e47f106-4a55-4542-a656-c49a71b0ede3"),
                            DefaultQuantity = 13,
                            ImageSource = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/607dfd53-5b5c-4309-9e1f-5a959d20e16c/Derivates/9ac9e3c1-20d2-4d31-afdb-191c9ba22235.jpg",
                            Name = "Jelly"
                        },
                        new
                        {
                            Id = new Guid("d5d582a4-0a16-4c8e-b680-dc1711c1867d"),
                            DefaultQuantity = 10,
                            ImageSource = "https://www.wholesomeyum.com/wp-content/uploads/2017/03/wholesomeyum-Low-Carb-Keto-Pancakes-Recipe-21.jpg",
                            Name = "Pancake"
                        },
                        new
                        {
                            Id = new Guid("3e883ff9-9a14-467d-9442-4913487ceb4b"),
                            DefaultQuantity = 9,
                            ImageSource = "https://media.istockphoto.com/photos/fresh-citrus-juices-picture-id158268808?k=20&m=158268808&s=612x612&w=0&h=9mUMCBDaY-JYqR7m9r_mi0-Ta0RIebZ3DpxyimSQ7Fc=",
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("e758f9db-8764-455f-8859-11ecd11cf977"),
                            DefaultQuantity = 7,
                            ImageSource = "https://img.freepik.com/free-vector/soda-cups-drink_24877-57922.jpg?w=2000",
                            Name = "Soda"
                        });
                });

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.HasOne("Entities.Models.FridgeModel", "FridgeModel")
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeModel");
                });

            modelBuilder.Entity("Entities.Models.FridgeProduct", b =>
                {
                    b.HasOne("Entities.Models.Fridge", "Fridge")
                        .WithMany("Products")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Fridges")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.FridgeModel", b =>
                {
                    b.Navigation("Fridges");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Fridges");
                });
#pragma warning restore 612, 618
        }
    }
}
