// <auto-generated />
using System;
using Entities.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            FridgeModelId = new Guid("a57f4319-b951-40e9-92b3-eac5fba21003"),
                            Name = "Samsung",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            FridgeModelId = new Guid("35771bd8-26bd-497b-938c-a55099f952c2"),
                            Name = "Bosch",
                            OwnerName = "Anna"
                        },
                        new
                        {
                            Id = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            FridgeModelId = new Guid("ecf08f01-0604-4c7c-9234-5d9f345734c0"),
                            Name = "Indesit",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            FridgeModelId = new Guid("5d643efa-3320-4602-b34f-ad683c6a1e9d"),
                            Name = "Philips",
                            OwnerName = "Kirill"
                        },
                        new
                        {
                            Id = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            FridgeModelId = new Guid("97e496af-060b-477d-a285-847f4991dfd8"),
                            Name = "Beko",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            FridgeModelId = new Guid("a57f4319-b951-40e9-92b3-eac5fba21003"),
                            Name = "Samsung",
                            OwnerName = "Kirill"
                        },
                        new
                        {
                            Id = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            FridgeModelId = new Guid("7a5521f6-c232-4938-9804-acd18d1c6b67"),
                            Name = "Indesit",
                            OwnerName = "Kirill"
                        },
                        new
                        {
                            Id = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            FridgeModelId = new Guid("5d643efa-3320-4602-b34f-ad683c6a1e9d"),
                            Name = "Philips",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            FridgeModelId = new Guid("5d643efa-3320-4602-b34f-ad683c6a1e9d"),
                            Name = "Beko",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            FridgeModelId = new Guid("9cdeb1aa-0036-41b7-855f-50b7df8b6a9c"),
                            Name = "Liebherr",
                            OwnerName = "Polina"
                        },
                        new
                        {
                            Id = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            FridgeModelId = new Guid("0977597e-b6ab-4960-8ac1-4ed96224ca04"),
                            Name = "Vestfrost",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            FridgeModelId = new Guid("787d1096-7547-4a5e-b0e9-af06789682f1"),
                            Name = "Bosch",
                            OwnerName = "Mariya"
                        },
                        new
                        {
                            Id = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            FridgeModelId = new Guid("89432c98-ed08-4f29-ad65-c048aa54e66f"),
                            Name = "Atlant",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            FridgeModelId = new Guid("636c9cc3-6d74-4d18-a236-55b3b6b36271"),
                            Name = "Liebherr",
                            OwnerName = "Nastya"
                        },
                        new
                        {
                            Id = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            FridgeModelId = new Guid("9cdeb1aa-0036-41b7-855f-50b7df8b6a9c"),
                            Name = "Vestfrost",
                            OwnerName = "Mariya"
                        },
                        new
                        {
                            Id = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            FridgeModelId = new Guid("70684b7d-92bf-49f1-bedb-ca7bc4ba4b14"),
                            Name = "Stinol",
                            OwnerName = "Vlada"
                        },
                        new
                        {
                            Id = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            FridgeModelId = new Guid("7a5521f6-c232-4938-9804-acd18d1c6b67"),
                            Name = "Indesit",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            FridgeModelId = new Guid("c227ed9e-4b5c-4d34-af1b-0956a0e883c4"),
                            Name = "Philips",
                            OwnerName = "Andrew"
                        },
                        new
                        {
                            Id = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            FridgeModelId = new Guid("c227ed9e-4b5c-4d34-af1b-0956a0e883c4"),
                            Name = "Philips",
                            OwnerName = "Kirill"
                        },
                        new
                        {
                            Id = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            FridgeModelId = new Guid("97e496af-060b-477d-a285-847f4991dfd8"),
                            Name = "Liebherr",
                            OwnerName = "Polina"
                        });
                });

            modelBuilder.Entity("Entities.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89432c98-ed08-4f29-ad65-c048aa54e66f"),
                            Name = "TH-803",
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("787d1096-7547-4a5e-b0e9-af06789682f1"),
                            Name = "514-NWE",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("70684b7d-92bf-49f1-bedb-ca7bc4ba4b14"),
                            Name = "RC-54",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("35771bd8-26bd-497b-938c-a55099f952c2"),
                            Name = "XM 4021-000",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("a57f4319-b951-40e9-92b3-eac5fba21003"),
                            Name = "DF 5180 W",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("c227ed9e-4b5c-4d34-af1b-0956a0e883c4"),
                            Name = "DS 333020",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("97e496af-060b-477d-a285-847f4991dfd8"),
                            Name = "VF 466 EB",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("9cdeb1aa-0036-41b7-855f-50b7df8b6a9c"),
                            Name = "KGN36S55",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("0977597e-b6ab-4960-8ac1-4ed96224ca04"),
                            Name = "RB-34 K6220SS",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("673099f8-5b2d-496c-8c02-0f0466a530b7"),
                            Name = "VF 910 X",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("da882f2b-a9d1-4885-ad7a-4fb21b037561"),
                            Name = "Electric MR-CR46G-HS-R",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("ecf08f01-0604-4c7c-9234-5d9f345734c0"),
                            Name = "RF-61 K90407F",
                            Year = 2013
                        },
                        new
                        {
                            Id = new Guid("7a5521f6-c232-4938-9804-acd18d1c6b67"),
                            Name = "SBS 7212",
                            Year = 2011
                        },
                        new
                        {
                            Id = new Guid("5d643efa-3320-4602-b34f-ad683c6a1e9d"),
                            Name = "VF 395-1 SBS",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("636c9cc3-6d74-4d18-a236-55b3b6b36271"),
                            Name = "RSA1SHVB1",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("Entities.Models.FridgeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e42a086-9c27-4ed8-bf20-9b5d1314b548"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("2e22820f-dd21-4698-95f3-aca3574db55d"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("a0727fce-fdab-4e90-ae51-c1e2edf8c566"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("723293b4-4431-49ab-91a4-280fe2801018"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("0da14e05-3453-4244-9fbe-8adb4d677910"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("4785a00b-818f-4107-9b4d-7ff1facbfd19"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("df76aeb1-3c2f-4f6a-bf7d-90d50847d2b4"),
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("df1d0cb9-3b15-4497-a430-f6b8d8e65ee4"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("38c1541f-7377-42fb-997e-9dc5d63541d9"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("1342c601-0e25-4825-b10f-49f04f055275"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("708ed2ce-7b1e-496b-a328-2ea4860921d3"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("8f753d8c-61ce-4b6c-b5be-daa3ae81986e"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("02c40018-8ef1-4761-bc14-2ad0524ddc90"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("0da14e05-3453-4244-9fbe-8adb4d677910"),
                            Quantity = 53
                        },
                        new
                        {
                            Id = new Guid("c0258c90-50cb-47d7-91a9-7d3b43b4d9e0"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("58dd9c8d-05c6-472c-9db6-e0fb6c40dd82"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("2e339d24-d484-43f7-b2f7-15a35634ceec"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("4f8aff52-28e0-4fff-b1cf-ede94b305844"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("58dd9c8d-05c6-472c-9db6-e0fb6c40dd82"),
                            Quantity = 36
                        },
                        new
                        {
                            Id = new Guid("9e1e6601-fd30-4137-9c03-7174c147b7be"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("7722ebfc-348b-4a21-b4c3-92885d502243"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("5caeaa73-eed6-4004-b87d-3cc8752a6385"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("739f2bf4-0f45-4e49-9a28-545d2480a4d3"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("23aac44b-85a8-4a8d-9186-d5c0a3b26804"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("2d9c1c30-ea45-4c31-bd85-23e8d3a1a51c"),
                            Quantity = 59
                        },
                        new
                        {
                            Id = new Guid("74d6f43d-57cb-4b8b-8470-58d5b86fc5cd"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("ceaff4f6-a3e0-438a-b26d-a5efe8f85aa1"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("06844d88-6246-4277-876e-18fcb2ee011a"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("fef3cfc6-7238-4bbe-9b5e-5892a66413f4"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("bcdac1da-a65e-43cd-9ea8-e6902292abbb"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("ec491952-30b7-4f54-8509-3795c1d412b0"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("81dbcbed-9504-4136-9927-21b10b04472f"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("e251d874-d59d-4b1c-b1bd-4f909df9f9e9"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("2ee38acf-ce7b-48a6-8cf2-7c093f8904a2"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("7ba69eed-abbd-487b-b431-1e445efcdd23"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("8f753d8c-61ce-4b6c-b5be-daa3ae81986e"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("eb8118ab-2e4e-4a77-9867-449b461ee9d1"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("214f319f-4a77-40a5-b386-8bb02531c72c"),
                            Quantity = 51
                        },
                        new
                        {
                            Id = new Guid("c949dc67-9313-4a78-989b-6c66802acabc"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 39
                        },
                        new
                        {
                            Id = new Guid("a6975f8d-e422-4271-b20d-5f19697f2519"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("10e854c7-c49c-4752-91c6-128abc68e3cb"),
                            Quantity = 61
                        },
                        new
                        {
                            Id = new Guid("5b77f46f-f7c1-4679-979b-a4619f1d1fc1"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("29800b01-12d3-48fe-a2b1-9683c54fb675"),
                            Quantity = 56
                        },
                        new
                        {
                            Id = new Guid("ec499ca0-16b6-4eef-b08c-7f8637ff8c69"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("e07d13af-670a-4007-81b0-fee1549a4cdd"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("b10a45f0-1669-48aa-819f-dc562d21763a"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("7ca21d7c-dc0b-43b5-ac90-ef067100a65a"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("415ace7f-56b2-4093-8b5b-482f26d59e88"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("d81a082d-5c06-4eec-8d53-a38802f5a63e"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("267b0412-ec7a-414b-8261-bcde651a5d8c"),
                            Quantity = 49
                        },
                        new
                        {
                            Id = new Guid("8b49fc8e-6489-4a78-8ee5-9f517ad207fe"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("a5d673b5-7e29-4e5a-9afb-2f08bdcce7f0"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("0c1fed35-91b5-42ef-ba68-fcf42ba0ef35"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("18b605cb-e711-4a41-a95c-5bcc68d1436d"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("62f6c28b-ed7d-4f4f-9d05-4e12d543c5cd"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("c99a9006-dbf3-4778-921f-ea445c747e47"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("a5d673b5-7e29-4e5a-9afb-2f08bdcce7f0"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("386f18ae-efe2-4914-a29b-2121eb9737fc"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("a5d673b5-7e29-4e5a-9afb-2f08bdcce7f0"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("8afdcee5-1d33-4938-b9ff-633451b8af4b"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("d49d8cd3-b65b-470a-a080-d87942589672"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("a0727fce-fdab-4e90-ae51-c1e2edf8c566"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("53848cb9-83e8-445b-945d-dce40ac8cc23"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("ceaff4f6-a3e0-438a-b26d-a5efe8f85aa1"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("05763bde-31fa-42a0-b4ea-b451d9cb32c5"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("d844ecc8-8cf9-485a-aaf1-73da20822d1f"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("fd845df3-f26d-4e35-8972-07654a7e834f"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("df76aeb1-3c2f-4f6a-bf7d-90d50847d2b4"),
                            Quantity = 51
                        },
                        new
                        {
                            Id = new Guid("4c5965c7-79b3-464d-b62b-b41db27ee496"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("ceaff4f6-a3e0-438a-b26d-a5efe8f85aa1"),
                            Quantity = 43
                        },
                        new
                        {
                            Id = new Guid("07f4450b-c789-4508-838c-b85b531a16a0"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("8f753d8c-61ce-4b6c-b5be-daa3ae81986e"),
                            Quantity = 36
                        },
                        new
                        {
                            Id = new Guid("1f41f786-6897-4550-81d6-f1b90bb6c9b4"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("c2c7ff40-c47e-4130-bdb7-2817bcb0c358"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            Quantity = 36
                        },
                        new
                        {
                            Id = new Guid("44c53c74-f86c-4832-8a1f-5d79d0eac619"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("29800b01-12d3-48fe-a2b1-9683c54fb675"),
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("70312332-696f-4319-841c-9e151a464bb5"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("10e854c7-c49c-4752-91c6-128abc68e3cb"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("2acdf4c5-0710-4dec-9af7-c91a8717df03"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("7722ebfc-348b-4a21-b4c3-92885d502243"),
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("2004a2ea-0df6-460a-9ac7-eec181744c34"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("2aef949d-09a2-49ff-b763-a74b3b464c7a"),
                            Quantity = 54
                        },
                        new
                        {
                            Id = new Guid("afe00aee-4393-462b-b260-712be381f9b0"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("a0727fce-fdab-4e90-ae51-c1e2edf8c566"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("c55ba825-2fe5-422e-a0ea-0afd1ed63b2f"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("35e4eb67-f7b2-4a73-be38-dedca8fbc7c4"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("739f2bf4-0f45-4e49-9a28-545d2480a4d3"),
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("51fbd1af-12fe-47b9-bc5e-b9e9b9a3c7e6"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("4c0305c5-66bd-42fd-a778-ce5eae0fadd8"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("cb3ede17-203b-4d62-86a6-58e6c450eab9"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("67a75e86-60c5-4ce5-95bc-484eda2e21b8"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("ea2d7c77-61e9-48e5-96ae-059738191711"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("bbf0f55c-d20a-4c2a-8215-fc65adacbafc"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("62f6c28b-ed7d-4f4f-9d05-4e12d543c5cd"),
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("6e84f67c-1028-43e0-86f7-ad28cbc35bb4"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            Quantity = 44
                        },
                        new
                        {
                            Id = new Guid("bc9c5286-73fc-40b3-b258-acf32beb446b"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("7ca21d7c-dc0b-43b5-ac90-ef067100a65a"),
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("92e4221f-2a14-4928-8ed7-c179257db54f"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 39
                        },
                        new
                        {
                            Id = new Guid("9ea75804-57d9-4b3a-a6a6-c2d410f081c0"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("5eef8641-4e7d-49df-81f6-52dc0e5e7610"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("82093098-15d2-4cc4-b8d3-67b66eee0a23"),
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("8c96dbd3-f12b-4493-a93f-120631af3e7a"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("cbd97226-5f63-4a98-832a-dbae809694f5"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("e251d874-d59d-4b1c-b1bd-4f909df9f9e9"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("0732192a-9455-496c-a6b4-5ac63e8e78dd"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("ea2d7c77-61e9-48e5-96ae-059738191711"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("0ff58656-eff5-4405-a0cf-105f23c53b27"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("82093098-15d2-4cc4-b8d3-67b66eee0a23"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("29358abe-91c4-4515-be3e-671b1d1671cc"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("a0727fce-fdab-4e90-ae51-c1e2edf8c566"),
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("a7e471e0-7517-4f7f-856c-ffec02d79e36"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("58dd9c8d-05c6-472c-9db6-e0fb6c40dd82"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("794cf8ba-ecd2-4dce-b7ed-12154122c704"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("0c8d3521-d24e-49e7-b56f-598fb443065a"),
                            Quantity = 67
                        },
                        new
                        {
                            Id = new Guid("050d1f6a-fe7a-4d70-9f57-f5bb07271661"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("ceaff4f6-a3e0-438a-b26d-a5efe8f85aa1"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("434f6fad-fc94-4358-ab36-cd2f9cca04f7"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("7722ebfc-348b-4a21-b4c3-92885d502243"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("a44457a7-b744-434b-858c-f825bedc7349"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("e07d13af-670a-4007-81b0-fee1549a4cdd"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("9a140fbf-a806-4474-b66d-68694fcd3cc9"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("93d913c6-5369-423f-8617-88cbe0462625"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("38c1541f-7377-42fb-997e-9dc5d63541d9"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("5d4b8561-4905-4146-9d1f-27ee7c92ad4e"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("ea2d7c77-61e9-48e5-96ae-059738191711"),
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("bfd5c4e9-085e-47bc-84e5-6b04dcef6b19"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("ec491952-30b7-4f54-8509-3795c1d412b0"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("fd8e5949-77ef-40a9-8bfa-4169d2ff082b"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("70707f26-d2c5-4308-8512-fd69b6dafe57"),
                            Quantity = 56
                        },
                        new
                        {
                            Id = new Guid("28e002d7-edb5-4c47-95ab-2444a12215a9"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("2d9c1c30-ea45-4c31-bd85-23e8d3a1a51c"),
                            Quantity = 39
                        },
                        new
                        {
                            Id = new Guid("823b340c-bc4d-4807-9b57-d88e362129fe"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("fef3cfc6-7238-4bbe-9b5e-5892a66413f4"),
                            Quantity = 43
                        },
                        new
                        {
                            Id = new Guid("ccb2475f-d660-42e4-ae4d-9ddb5f7fc2f4"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("d844ecc8-8cf9-485a-aaf1-73da20822d1f"),
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("9f18dacf-73d2-4671-be9c-3b624d8b2340"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("58dd9c8d-05c6-472c-9db6-e0fb6c40dd82"),
                            Quantity = 66
                        },
                        new
                        {
                            Id = new Guid("a740ba57-ac7b-4d23-a363-b18cdadf4072"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("e251d874-d59d-4b1c-b1bd-4f909df9f9e9"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f419e1fc-3b4a-4edf-9fc6-7b4f07ee2162"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("739f2bf4-0f45-4e49-9a28-545d2480a4d3"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("7a9820d5-a6fd-4db0-a08c-7a9448b1a684"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("58dd9c8d-05c6-472c-9db6-e0fb6c40dd82"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("203ebc35-c70b-4df3-abd5-16a5a9ce051a"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("22b511bb-bdd7-4224-a596-da3f2904f3ef"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("c4ef3177-49aa-46e9-9847-380a8cd228d4"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("0c8d3521-d24e-49e7-b56f-598fb443065a"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("241fe6b0-918e-4827-8fc8-236ebd0613a2"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("fef3cfc6-7238-4bbe-9b5e-5892a66413f4"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("d50fb274-39de-4620-8a2b-ea33b46259a8"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            Quantity = 80
                        },
                        new
                        {
                            Id = new Guid("e900cfbd-3f9a-4caa-bf1a-3b84ef0976b3"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("a018210b-34a6-4936-adfd-d71f847945e7"),
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("d73fbbe9-7cd6-4098-a855-c2a681f3fea1"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("29800b01-12d3-48fe-a2b1-9683c54fb675"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("dfd1f06d-cc27-43e7-a018-177f913fbbd2"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("f8a95b97-cbd7-4e6a-8207-5fb41f1320b9"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("d844ecc8-8cf9-485a-aaf1-73da20822d1f"),
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("fb533aaa-c435-48f9-af8d-2bf3b3037c93"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("d85bfcee-5cce-4608-b23a-76412aa8c196"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("fef3cfc6-7238-4bbe-9b5e-5892a66413f4"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("3efb0839-2d33-4736-8b5e-0cf97c2b98a3"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            Quantity = 42
                        },
                        new
                        {
                            Id = new Guid("7c5ec7f8-6922-4caf-9251-05e6515bbd76"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("62f6c28b-ed7d-4f4f-9d05-4e12d543c5cd"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("ee57c437-d61f-436c-b435-275eb0e99454"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("70707f26-d2c5-4308-8512-fd69b6dafe57"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("933173ad-5926-40d5-82eb-a041f112aca6"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("739f2bf4-0f45-4e49-9a28-545d2480a4d3"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f6f23a55-b466-4496-82dd-b5ae28afa3e5"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("67ff68c1-15c1-4799-98d2-14576be646c0"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("29800b01-12d3-48fe-a2b1-9683c54fb675"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("1e8f132c-e295-4e62-8d9d-08e803c11a40"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("a0727fce-fdab-4e90-ae51-c1e2edf8c566"),
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("8b84be2b-101d-48fb-96cd-25217ee24963"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("bb7243c7-85c4-4897-ace5-fd9569acda85"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("2aef949d-09a2-49ff-b763-a74b3b464c7a"),
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("5f24751f-1108-42f1-a4c8-57e473dfbcf5"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("267b0412-ec7a-414b-8261-bcde651a5d8c"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("ac0b5e8b-dab5-437d-8670-4c5dcd0d2098"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("3fedf8b0-73b2-4da1-8e8d-04855a166f7c"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("611b59fa-7792-44cc-8c92-cedaca53d7f2"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("d844ecc8-8cf9-485a-aaf1-73da20822d1f"),
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("8dbc81a8-0fed-4c37-8eb7-df54e3999b4c"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("2d9c1c30-ea45-4c31-bd85-23e8d3a1a51c"),
                            Quantity = 14
                        },
                        new
                        {
                            Id = new Guid("23820f1b-fe22-478b-8584-6de11c2fc412"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("62f6c28b-ed7d-4f4f-9d05-4e12d543c5cd"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("d4261d60-6b8d-4e40-87dd-0e47aaf36bf3"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("4fcc4443-dc6e-476b-b263-bd62edf72187"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("0da14e05-3453-4244-9fbe-8adb4d677910"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("d30bcbcd-dd8b-4ad8-a6c8-1767372cfc82"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("214f319f-4a77-40a5-b386-8bb02531c72c"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("b44c8c6e-36f5-48b8-9b71-7541e4bc624b"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("df76aeb1-3c2f-4f6a-bf7d-90d50847d2b4"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("53acf3a2-2722-46a3-b2c5-73c5ee9f185f"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("a018210b-34a6-4936-adfd-d71f847945e7"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("89bfd518-364a-4fd0-a592-dee5bb3d364a"),
                            FridgeId = new Guid("9ca69a10-1689-4de6-8a70-87522495fa30"),
                            ProductId = new Guid("3fedf8b0-73b2-4da1-8e8d-04855a166f7c"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("150fb49b-e3f2-494c-946a-7872c42ee57e"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("3fedf8b0-73b2-4da1-8e8d-04855a166f7c"),
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("431cd348-fdff-40f5-a7ef-e277cf06bf61"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("0c8d3521-d24e-49e7-b56f-598fb443065a"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("8f69b08f-bdef-4ede-9f99-51b4a0ca6268"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("38c1541f-7377-42fb-997e-9dc5d63541d9"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("8e8e737f-de53-4608-bf4a-9cb0a39a8bfe"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("cc9da592-7f56-4412-b49d-c79c4c23a59b"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("1b00ed2a-d906-458e-a016-2e4077e55ccb"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("e07d13af-670a-4007-81b0-fee1549a4cdd"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("6cd88648-63a7-4208-81d2-be6298986f46"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("df76aeb1-3c2f-4f6a-bf7d-90d50847d2b4"),
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("22251f50-0a29-4c5c-8e39-22fd9a14bde4"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("10e854c7-c49c-4752-91c6-128abc68e3cb"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("aa853841-2bd4-49a2-9af0-c88e44eb8328"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("22b511bb-bdd7-4224-a596-da3f2904f3ef"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("aefd32a3-ee91-49b7-94c9-f9b60da119de"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("009503e6-c3b7-40c6-8501-b339833e9123"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("22b511bb-bdd7-4224-a596-da3f2904f3ef"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("c40845f2-98bb-42c2-9f61-271c6e4b1816"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("a9d3c244-a823-447c-81a6-27a59852830e"),
                            FridgeId = new Guid("4d40b3e7-dae1-4410-8619-a16a9646c445"),
                            ProductId = new Guid("ea2d7c77-61e9-48e5-96ae-059738191711"),
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("8f24055d-4cb1-4c1e-9fd5-6d8f8c7422aa"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("e07d13af-670a-4007-81b0-fee1549a4cdd"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("4e263d7c-420b-4c3f-ad60-cd136c57e95a"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("ec491952-30b7-4f54-8509-3795c1d412b0"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("df683b64-3bda-4cfc-9a94-9884188298c8"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("7ca21d7c-dc0b-43b5-ac90-ef067100a65a"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("a0d636d0-4004-4b11-96f1-977c26342982"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("10e854c7-c49c-4752-91c6-128abc68e3cb"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("d45a031c-14be-4593-b1d9-8d4d9d2ff263"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("214f319f-4a77-40a5-b386-8bb02531c72c"),
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("ddbaa6f1-e6aa-43d2-85e1-6e06b695f81d"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("491801ca-9589-4897-bca4-132810d6f7d0"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("29800b01-12d3-48fe-a2b1-9683c54fb675"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("cf1d19ea-ce44-4622-b05e-59c10f427a8b"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("82093098-15d2-4cc4-b8d3-67b66eee0a23"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("4cfef9dc-df64-41ee-9a5d-3b5be3d3a1cd"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("665efce3-80d0-465d-b841-5ccb0e425ade"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("2aef949d-09a2-49ff-b763-a74b3b464c7a"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("8a9aa61f-ea86-47e1-a00d-0b1afffebc99"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("214f319f-4a77-40a5-b386-8bb02531c72c"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("5551067f-4f44-4ab2-8d18-412bdb260bc0"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("0da14e05-3453-4244-9fbe-8adb4d677910"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("33d47fe9-0541-4fa0-9f0b-ecd97610973f"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("62f6c28b-ed7d-4f4f-9d05-4e12d543c5cd"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("b95e40a8-0f3d-4440-b402-06c78e8c3511"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("8f753d8c-61ce-4b6c-b5be-daa3ae81986e"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("255a0e43-f42c-458c-a247-2ce9a26612af"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("a018210b-34a6-4936-adfd-d71f847945e7"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("65ded067-609c-4065-b1c7-e6127b2295ec"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("2902784d-09e2-49b4-bdaf-bcb6a391416f"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("47d660c9-460a-4da8-b7bb-8685b2528f5a"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("2aef949d-09a2-49ff-b763-a74b3b464c7a"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("03527ffd-d4fa-45ac-9951-824a32bb8d42"),
                            FridgeId = new Guid("3d683e69-5118-489c-ba23-94a14836ee2d"),
                            ProductId = new Guid("e251d874-d59d-4b1c-b1bd-4f909df9f9e9"),
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("391294ab-2430-453b-9c4e-311d253bb48d"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("fbfd03a5-0ca2-42b6-831e-c8e24fa74358"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("362e69e4-0491-441c-b283-b349bbf196bd"),
                            FridgeId = new Guid("f5de0450-7ded-40ab-9d2f-546851161b6f"),
                            ProductId = new Guid("0da14e05-3453-4244-9fbe-8adb4d677910"),
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("06775948-535f-4bbe-bb65-64e7165b1f18"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("d844ecc8-8cf9-485a-aaf1-73da20822d1f"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("d55c98d0-b0d5-4c25-9606-a07cec6c933e"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("ec491952-30b7-4f54-8509-3795c1d412b0"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("569d8813-eac6-44bc-ac73-adb4b5fccb3c"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("52b0b148-b007-4531-a688-c288eaa8807c"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("8f753d8c-61ce-4b6c-b5be-daa3ae81986e"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("21efd648-c21e-4d02-8996-2096d25ee424"),
                            FridgeId = new Guid("68d87710-9322-4143-95f7-b0462c8741ca"),
                            ProductId = new Guid("cb3ede17-203b-4d62-86a6-58e6c450eab9"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("1aba23c0-0f84-4270-a9e5-187cc352bada"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("f3029c17-29aa-4fc9-bd3d-a2736d0d8aac"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("175738c6-354b-47a3-a301-9b2ffdea648d"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("267b0412-ec7a-414b-8261-bcde651a5d8c"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("56950507-fe6d-43d5-8432-bc0a09d1cd7c"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("a018210b-34a6-4936-adfd-d71f847945e7"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("946e5d65-fadd-45cb-a86a-49784f0be5e8"),
                            FridgeId = new Guid("2921fe0c-f6f2-4939-923e-8fd878c1c243"),
                            ProductId = new Guid("a018210b-34a6-4936-adfd-d71f847945e7"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("00e4f7eb-d5fa-45df-9cf4-22d40b471374"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("81496350-f60c-46b4-831d-87447f304647"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("2d9c1c30-ea45-4c31-bd85-23e8d3a1a51c"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("2102e762-84d4-4a3d-a050-8f3170ecc0b6"),
                            FridgeId = new Guid("2a2a9044-813d-44ac-ad8a-80f377bef1db"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("035659fd-eb84-425c-8b0a-7e6a75e5c96a"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("82093098-15d2-4cc4-b8d3-67b66eee0a23"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("4a82f30a-48bb-4deb-8a83-39ec9b3c9723"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("ceaff4f6-a3e0-438a-b26d-a5efe8f85aa1"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("926a8b73-3beb-44b9-862f-3a95600c1c73"),
                            FridgeId = new Guid("db6c1c25-77ed-456c-8dd7-e9e491a62f35"),
                            ProductId = new Guid("22b511bb-bdd7-4224-a596-da3f2904f3ef"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("dc22fa9b-3b4e-40be-a519-31c7007e4713"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("70707f26-d2c5-4308-8512-fd69b6dafe57"),
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("77087145-9ad3-4ec3-b27e-5f7eb14827eb"),
                            FridgeId = new Guid("16ceb523-89fb-4141-9d0b-a9d94dd9e4d3"),
                            ProductId = new Guid("a5d673b5-7e29-4e5a-9afb-2f08bdcce7f0"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("ec9e7d6b-0974-4818-a3f1-165b463e3e39"),
                            FridgeId = new Guid("570a85c1-3431-4875-9844-b3b91d0dbc5f"),
                            ProductId = new Guid("267b0412-ec7a-414b-8261-bcde651a5d8c"),
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("cfa06e20-e696-4922-9d92-cf1be5bfdd15"),
                            FridgeId = new Guid("4e189220-d31b-4cef-a19c-82f5acc92dc6"),
                            ProductId = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("89b6d3a8-0f27-4885-847c-786515f7a145"),
                            FridgeId = new Guid("957d2895-38d4-4ae0-96c1-1d7a87fdc6bc"),
                            ProductId = new Guid("ea2d7c77-61e9-48e5-96ae-059738191711"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("ab09ad9b-3026-4f7b-925c-a045db9da27f"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("0c8d3521-d24e-49e7-b56f-598fb443065a"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("17140e5b-259d-46e0-b465-c332234702ab"),
                            FridgeId = new Guid("467a286d-fb73-47e4-9696-5c7e9efe36ed"),
                            ProductId = new Guid("7ca21d7c-dc0b-43b5-ac90-ef067100a65a"),
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("ffee1fe5-92f9-4937-9037-95ba63d34f94"),
                            FridgeId = new Guid("e8c640e8-f666-4341-8e6e-f15b9d3a32e5"),
                            ProductId = new Guid("38c1541f-7377-42fb-997e-9dc5d63541d9"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("3d8fba9a-84df-423b-a93e-d49bec3db333"),
                            FridgeId = new Guid("ea581127-602c-4f5e-b601-b61da930855e"),
                            ProductId = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("ac66dccc-ac51-489c-b6ce-caee5c194b53"),
                            FridgeId = new Guid("1bc3301d-e132-41d7-b4d5-6fb639aac4c1"),
                            ProductId = new Guid("ec491952-30b7-4f54-8509-3795c1d412b0"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("93bbea34-d46f-4341-823d-a75eab213107"),
                            FridgeId = new Guid("1eca9dd4-85c1-4f39-a298-e18a8f435db2"),
                            ProductId = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("c57f157c-ab83-4c47-b972-6c927ac248f7"),
                            FridgeId = new Guid("3dddc8a5-d1d4-428a-9552-f62b6728bac5"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("3e0cc690-6878-4899-9ef6-8e23d2ee6f9e"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("653bdacd-131c-4011-aab2-a0c65c1c933f"),
                            FridgeId = new Guid("7d9663ec-ff37-4dd3-9a14-1eb6d6f7d8df"),
                            ProductId = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("3ddab5d6-84f5-4c43-a97c-3a7f456422e3"),
                            FridgeId = new Guid("ffe5652b-5cc1-4cb2-9976-aba17cff3f67"),
                            ProductId = new Guid("3fedf8b0-73b2-4da1-8e8d-04855a166f7c"),
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22b511bb-bdd7-4224-a596-da3f2904f3ef"),
                            DefaultQuantity = 15,
                            Name = "Bread"
                        },
                        new
                        {
                            Id = new Guid("214f319f-4a77-40a5-b386-8bb02531c72c"),
                            DefaultQuantity = 15,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("a5d673b5-7e29-4e5a-9afb-2f08bdcce7f0"),
                            DefaultQuantity = 17,
                            Name = "Yoghurt"
                        },
                        new
                        {
                            Id = new Guid("38c1541f-7377-42fb-997e-9dc5d63541d9"),
                            DefaultQuantity = 16,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = new Guid("8f753d8c-61ce-4b6c-b5be-daa3ae81986e"),
                            DefaultQuantity = 16,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("29800b01-12d3-48fe-a2b1-9683c54fb675"),
                            DefaultQuantity = 13,
                            Name = "Mashroom"
                        },
                        new
                        {
                            Id = new Guid("3fedf8b0-73b2-4da1-8e8d-04855a166f7c"),
                            DefaultQuantity = 6,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = new Guid("ec491952-30b7-4f54-8509-3795c1d412b0"),
                            DefaultQuantity = 6,
                            Name = "Pork"
                        },
                        new
                        {
                            Id = new Guid("62f6c28b-ed7d-4f4f-9d05-4e12d543c5cd"),
                            DefaultQuantity = 15,
                            Name = "Beef"
                        },
                        new
                        {
                            Id = new Guid("ea2d7c77-61e9-48e5-96ae-059738191711"),
                            DefaultQuantity = 8,
                            Name = "Sausage"
                        },
                        new
                        {
                            Id = new Guid("a1fef996-b37c-44b7-846a-d5363d25e762"),
                            DefaultQuantity = 14,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("ceaff4f6-a3e0-438a-b26d-a5efe8f85aa1"),
                            DefaultQuantity = 7,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = new Guid("fef3cfc6-7238-4bbe-9b5e-5892a66413f4"),
                            DefaultQuantity = 13,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("3cec2a04-0e6d-4608-bd82-6aa0e479f615"),
                            DefaultQuantity = 6,
                            Name = "Beans"
                        },
                        new
                        {
                            Id = new Guid("2aef949d-09a2-49ff-b763-a74b3b464c7a"),
                            DefaultQuantity = 11,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = new Guid("10e854c7-c49c-4752-91c6-128abc68e3cb"),
                            DefaultQuantity = 11,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = new Guid("2d9c1c30-ea45-4c31-bd85-23e8d3a1a51c"),
                            DefaultQuantity = 15,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = new Guid("e251d874-d59d-4b1c-b1bd-4f909df9f9e9"),
                            DefaultQuantity = 14,
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("739f2bf4-0f45-4e49-9a28-545d2480a4d3"),
                            DefaultQuantity = 7,
                            Name = "Potato"
                        },
                        new
                        {
                            Id = new Guid("82093098-15d2-4cc4-b8d3-67b66eee0a23"),
                            DefaultQuantity = 6,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = new Guid("e07d13af-670a-4007-81b0-fee1549a4cdd"),
                            DefaultQuantity = 11,
                            Name = "Cherry"
                        },
                        new
                        {
                            Id = new Guid("7722ebfc-348b-4a21-b4c3-92885d502243"),
                            DefaultQuantity = 17,
                            Name = "Grape"
                        },
                        new
                        {
                            Id = new Guid("cb3ede17-203b-4d62-86a6-58e6c450eab9"),
                            DefaultQuantity = 14,
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = new Guid("a018210b-34a6-4936-adfd-d71f847945e7"),
                            DefaultQuantity = 6,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = new Guid("267b0412-ec7a-414b-8261-bcde651a5d8c"),
                            DefaultQuantity = 11,
                            Name = "Peach"
                        },
                        new
                        {
                            Id = new Guid("0c8d3521-d24e-49e7-b56f-598fb443065a"),
                            DefaultQuantity = 16,
                            Name = "Strawberry"
                        },
                        new
                        {
                            Id = new Guid("a0727fce-fdab-4e90-ae51-c1e2edf8c566"),
                            DefaultQuantity = 9,
                            Name = "Raspberry"
                        },
                        new
                        {
                            Id = new Guid("6f911a57-e7a3-4ff5-84af-50644af5eba5"),
                            DefaultQuantity = 9,
                            Name = "Watermelon"
                        },
                        new
                        {
                            Id = new Guid("df76aeb1-3c2f-4f6a-bf7d-90d50847d2b4"),
                            DefaultQuantity = 15,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = new Guid("18ef1ad3-45eb-4f81-b2a4-d4edefd0eb67"),
                            DefaultQuantity = 7,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = new Guid("4124cddb-9ab2-418c-ae07-f28ef8c9d9b6"),
                            DefaultQuantity = 6,
                            Name = "Kefir"
                        },
                        new
                        {
                            Id = new Guid("c0ee6038-f5e2-4fa1-a8fe-4b0d175d3c17"),
                            DefaultQuantity = 5,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = new Guid("58dd9c8d-05c6-472c-9db6-e0fb6c40dd82"),
                            DefaultQuantity = 15,
                            Name = "Jam"
                        },
                        new
                        {
                            Id = new Guid("70707f26-d2c5-4308-8512-fd69b6dafe57"),
                            DefaultQuantity = 14,
                            Name = "Pudding"
                        },
                        new
                        {
                            Id = new Guid("0da14e05-3453-4244-9fbe-8adb4d677910"),
                            DefaultQuantity = 13,
                            Name = "Jelly"
                        },
                        new
                        {
                            Id = new Guid("d844ecc8-8cf9-485a-aaf1-73da20822d1f"),
                            DefaultQuantity = 12,
                            Name = "Pancake"
                        },
                        new
                        {
                            Id = new Guid("7ca21d7c-dc0b-43b5-ac90-ef067100a65a"),
                            DefaultQuantity = 16,
                            Name = "Juice"
                        },
                        new
                        {
                            Id = new Guid("3c1a0f0e-90e9-48cc-9fd4-d38deac70b52"),
                            DefaultQuantity = 8,
                            Name = "Soda"
                        });
                });

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.HasOne("Entities.Models.FridgeModel", "FridgeModel")
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FridgeModel");
                });

            modelBuilder.Entity("Entities.Models.FridgeProduct", b =>
                {
                    b.HasOne("Entities.Models.Fridge", "Fridge")
                        .WithMany("Products")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Fridge", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.FridgeModel", b =>
                {
                    b.Navigation("Fridges");
                });
#pragma warning restore 612, 618
        }
    }
}
